"use client";
import { TableSurface } from "@serviceos/design-system";
import React, { useCallback, useState } from "react";
import { Download, Eye, RefreshCw, RotateCw, Search, XCircle } from "lucide-react";
import { Badge, Btn, Card, EmptyState, Input, Modal, Pagination, Select, Skeleton } from "../../../components/shared/ui";
import { sprint27AdminApi, type NotificationOutboxRecord } from "../../../lib/api";
import { useAction, useApi } from "../../../hooks/useApi";

const PAGE_SIZE = 25;
const STATUS_VARIANT: Record<string, "success" | "warning" | "danger" | "muted"> = { delivered: "success", sent: "success", pending: "warning", queued: "warning", failed: "danger", skipped: "muted", provider_not_configured: "muted", preference_disabled: "muted" };

export function LogsFailuresPanel() {
  const [status, setStatus] = useState(""); const [channel, setChannel] = useState(""); const [recipient, setRecipient] = useState(""); const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  const [selected, setSelected] = useState<NotificationOutboxRecord | null>(null); const [workingId, setWorkingId] = useState<string | null>(null); const [notice, setNotice] = useState<{ ok: boolean; text: string } | null>(null);
  const outbox = useApi(useCallback(() => sprint27AdminApi.listOutbox({ delivery_status: status || undefined, channel: channel || undefined, recipient_type: recipient || undefined, search: search || undefined, limit: PAGE_SIZE, offset: (page - 1) * PAGE_SIZE } as Record<string, string | number>), [status, channel, recipient, search, page]));
  const retry = useAction((id: string) => sprint27AdminApi.retryOutbox(id)); const cancel = useAction((id: string) => sprint27AdminApi.cancelOutbox(id));
  function changeFilter(setter: (v: string) => void, value: string) { setter(value); setPage(1); }
  async function handleRetry(id: string) { setWorkingId(id); const result = await retry.execute(id); setWorkingId(null); if (result) { setNotice({ ok: true, text: "Delivery returned to the pending queue without creating a duplicate." }); outbox.refetch(); } else setNotice({ ok: false, text: retry.error ?? "Retry was not accepted." }); }
  async function handleCancel(id: string) { setWorkingId(id); const result = await cancel.execute(id); setWorkingId(null); if (result) { setNotice({ ok: true, text: "Pending delivery cancelled before dispatch." }); outbox.refetch(); } else setNotice({ ok: false, text: cancel.error ?? "Only a pending delivery can be cancelled." }); }
  async function handleExport() { try { const data = await sprint27AdminApi.exportOutbox({ delivery_status: status || undefined, channel: channel || undefined, recipient_type: recipient || undefined, search: search || undefined }); const columns = ["id", "created_at", "channel", "recipient_type", "delivery_status", "provider_name", "retry_count", "failure_code", "template_key"]; const csv = [columns.join(","), ...data.items.map(row => columns.map(key => `"${String(row[key] ?? "").replace(/"/g, '""')}"`).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = `notification-delivery-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); setNotice({ ok: true, text: `Exported ${data.items.length} matching records (operational export limit: 200).` }); } catch (e) { setNotice({ ok: false, text: e instanceof Error ? e.message : "Export failed." }); } }
  const rows = outbox.data?.items ?? [];
  return <div className="nc-stack">
    {notice && <div className={`nc-message ${notice.ok ? "success" : "danger"}`}>{notice.text}</div>}
    <Card padding={0}><div className="nc-filterbar"><div className="nc-search"><Search size={15}/><Input placeholder="Search delivery, recipient, template, or failure" value={search} onChange={v => changeFilter(setSearch, v)}/></div><Select value={status} onChange={v => changeFilter(setStatus, v)} options={[{ value: "", label: "All delivery states" }, { value: "delivered", label: "Delivered" }, { value: "pending", label: "Pending" }, { value: "failed", label: "Failed" }, { value: "skipped", label: "Cancelled / skipped" }, { value: "provider_not_configured", label: "Provider unavailable" }, { value: "preference_disabled", label: "Preference disabled" }]}/><Select value={channel} onChange={v => changeFilter(setChannel, v)} options={[{ value: "", label: "All channels" }, { value: "in_app", label: "In-app" }, { value: "email", label: "Email" }, { value: "sms", label: "SMS" }, { value: "whatsapp", label: "WhatsApp" }, { value: "push", label: "Push" }]}/><Select value={recipient} onChange={v => changeFilter(setRecipient, v)} options={[{ value: "", label: "All recipients" }, { value: "admin", label: "Admin" }, { value: "provider", label: "Provider" }, { value: "customer", label: "Customer" }, { value: "staff", label: "Staff" }]}/><Btn size="sm" variant="ghost" onClick={outbox.refetch}><RefreshCw size={14}/></Btn><Btn size="sm" variant="secondary" onClick={handleExport}><Download size={14}/> Export CSV</Btn></div>
      {outbox.error ? <div className="nc-empty-error">{outbox.error}{outbox.requestId ? ` · ${outbox.requestId}` : ""}</div> : outbox.loading ? <div style={{ padding: 18 }}>{Array.from({ length: 7 }, (_, i) => <Skeleton key={i} height={48} style={{ marginBottom: 8 }}/>)}</div> : rows.length === 0 ? <EmptyState title="No delivery attempts match" description={outbox.data?.total === 0 && !status && !channel && !recipient && !search ? "The outbox is connected and empty. Delivery traces will appear as notifications are generated." : "Clear or change the filters to widen the result set."}/> : <div style={{ overflowX: "auto" }}><TableSurface className="nc-table"><thead><tr><th>Delivery</th><th>Recipient</th><th>Channel</th><th>Provider</th><th>Status</th><th>Attempts</th><th>Created</th><th></th></tr></thead><tbody>{rows.map(row => <tr key={row.id}><td><div className="nc-notif-title">{row.title}</div><code style={{ fontSize: 10, color: "var(--text-tertiary)" }}>{row.id.slice(0, 12)} · {row.template_key}</code></td><td>{row.recipient_type}<div style={{ fontSize: 10, color: "var(--text-tertiary)" }}>{row.recipient_user_id?.slice(0, 12) ?? "No user"}</div></td><td><Badge variant="muted">{row.channel.replace("_", "-")}</Badge></td><td>{row.provider_name ?? "Not assigned"}</td><td><Badge variant={STATUS_VARIANT[row.delivery_status] ?? "muted"}>{row.delivery_status.replace(/_/g, " ")}</Badge>{row.failure_code && <div style={{ color: "var(--danger-text)", fontSize: 10, marginTop: 3 }}>{row.failure_code}</div>}</td><td>{row.retry_count} / {row.max_retries}</td><td>{new Date(row.created_at).toLocaleString()}</td><td><div style={{ display: "flex", gap: 4 }}><Btn size="xs" variant="ghost" onClick={() => setSelected(row)}><Eye size={12}/></Btn>{row.delivery_status === "failed" && row.retry_count < row.max_retries && <Btn size="xs" variant="secondary" loading={workingId === row.id} onClick={() => handleRetry(row.id)}><RotateCw size={12}/></Btn>}{row.delivery_status === "pending" && <Btn size="xs" variant="ghost" loading={workingId === row.id} onClick={() => handleCancel(row.id)}><XCircle size={12}/></Btn>}</div></td></tr>)}</tbody></TableSurface></div>}
      <Pagination page={page} total={outbox.data?.total ?? 0} pageSize={PAGE_SIZE} onPage={setPage}/>
    </Card>
    {selected && <Modal open onClose={() => setSelected(null)} title="Delivery trace" size="lg"><div className="nc-stack"><div style={{ display: "flex", gap: 7 }}><Badge variant={STATUS_VARIANT[selected.delivery_status] ?? "muted"}>{selected.delivery_status.replace(/_/g, " ")}</Badge><Badge variant="muted">{selected.channel}</Badge></div><Trace label="Delivery ID" value={selected.id}/><Trace label="Event ID" value={selected.notification_event_id ?? "Not linked"}/><Trace label="Recipient" value={`${selected.recipient_type} · ${selected.recipient_user_id ?? "No user"}`}/><Trace label="Template" value={selected.template_key}/><Trace label="Message" value={`${selected.title}\n${selected.body}`}/><Trace label="Provider" value={selected.provider_name ?? "Not assigned"}/><Trace label="Failure" value={selected.failure_code ? `${selected.failure_code}: ${selected.failure_message ?? "No provider detail"}` : "None"}/><Trace label="Timing" value={`Created ${new Date(selected.created_at).toLocaleString()} · Sent ${selected.sent_at ? new Date(selected.sent_at).toLocaleString() : "not sent"} · Delivered ${selected.delivered_at ? new Date(selected.delivered_at).toLocaleString() : "not delivered"}`}/><div style={{ display: "flex", justifyContent: "flex-end" }}><Btn variant="ghost" onClick={() => setSelected(null)}>Close</Btn></div></div></Modal>}
  </div>;
}
function Trace({ label, value }: { label: string; value: string }) { return <div><div style={{ fontSize: 10, textTransform: "uppercase", letterSpacing: ".07em", color: "var(--text-tertiary)", fontWeight: 800, marginBottom: 4 }}>{label}</div><div style={{ padding: "9px 11px", borderRadius: 8, background: "var(--surface-sunken)", color: "var(--text-primary)", fontSize: 12, whiteSpace: "pre-wrap", wordBreak: "break-word" }}>{value}</div></div>; }
