"use client";
import { TableSurface } from "@serviceos/design-system";

import React, { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, Bell, CheckCheck, CircleAlert, CreditCard, Eye, FileText, HardDrive, LayoutList, MailCheck, RefreshCw, Route, Search, Settings2, SlidersHorizontal } from "lucide-react";
import { AdminLayout } from "../../../components/layout/AdminLayout";
import { Badge, Btn, Card, EmptyState, Input, Modal, Pagination, SectionHeader, Select, Skeleton, Spinner } from "../../../components/shared/ui";
import { sprint27AdminApi, type InAppNotification, type NotificationPreferenceEvent } from "../../../lib/api";
import { useAction, useApi } from "../../../hooks/useApi";
import { RuntimeTemplatesPanel } from "./RuntimeTemplatesPanel";
import { EventPoliciesPanel } from "./EventPoliciesPanel";
import { DeliveryProvidersPanel } from "./DeliveryProvidersPanel";
import { PaymentGatewayPanel } from "./PaymentGatewayPanel";
import { StorageConfigPanel } from "./StorageConfigPanel";
import { LogsFailuresPanel } from "./LogsFailuresPanel";

type Tab = "feed" | "templates" | "policies" | "providers" | "payments" | "storage" | "logs" | "settings";
const PAGE_SIZE = 25;
const TABS: { key: Tab; label: string; icon: React.ReactNode; description: string }[] = [
  { key: "feed", label: "Admin inbox", icon: <LayoutList size={15}/>, description: "Alerts addressed to your administrator account" },
  { key: "templates", label: "Templates", icon: <FileText size={15}/>, description: "Copy used by the live outbox pipeline" },
  { key: "policies", label: "Event policies", icon: <Route size={15}/>, description: "Versioned delivery and recipient rules" },
  { key: "providers", label: "Channels", icon: <MailCheck size={15}/>, description: "Real provider connectivity and health" },
  { key: "payments", label: "Payment gateway", icon: <CreditCard size={15}/>, description: "Razorpay credentials for checkout, webhooks, and reconciliation" },
  { key: "storage", label: "Media storage", icon: <HardDrive size={15}/>, description: "Cloudinary credentials for uploaded photos, logos, icons and documents" },
  { key: "logs", label: "Delivery logs", icon: <Activity size={15}/>, description: "Trace, retry, and cancel queued deliveries" },
  { key: "settings", label: "My alerts", icon: <Settings2 size={15}/>, description: "Personal preferences for admin-directed events" },
];
const SEVERITY_VARIANT: Record<string, "danger" | "warning" | "success" | "muted"> = { critical: "danger", high: "danger", warning: "warning", medium: "warning", success: "success", low: "muted", info: "muted" };

function useDebounced(value: string, delay = 300) {
  const [debounced, setDebounced] = useState(value);
  useEffect(() => { const id = setTimeout(() => setDebounced(value), delay); return () => clearTimeout(id); }, [value, delay]);
  return debounced;
}

function Toggle({ checked, disabled, busy, label, onChange }: { checked: boolean; disabled?: boolean; busy?: boolean; label: string; onChange: () => void }) {
  return <button type="button" role="switch" aria-checked={checked} aria-label={label} disabled={disabled || busy} onClick={onChange} className="nc-switch" data-on={checked ? "true" : "false"} title={disabled ? label : checked ? "Disable" : "Enable"}><span/></button>;
}

function NotificationSettingsPanel() {
  const catalog = useApi(useCallback(() => sprint27AdminApi.getPreferenceCatalog(), []), []);
  const [query, setQuery] = useState(""); const [source, setSource] = useState("");
  const [saving, setSaving] = useState<string | null>(null);
  const [optimistic, setOptimistic] = useState<Record<string, boolean>>({});
  const [message, setMessage] = useState<{ ok: boolean; text: string } | null>(null);
  const events = useMemo(() => { const q = query.trim().toLowerCase(); return (catalog.data?.items ?? []).filter(event => (!source || event.source_engine === source) && (!q || event.event_name.toLowerCase().includes(q) || event.event_key.toLowerCase().includes(q))); }, [catalog.data, query, source]);
  const sources = Array.from(new Set((catalog.data?.items ?? []).map(e => e.source_engine))).sort();
  const providers = catalog.data?.providers ?? []; const liveChannels = providers.filter(p => p.configured).length;
  async function toggle(event: NotificationPreferenceEvent, channel: string, current: boolean) {
    const key = `${event.event_key}::${channel}`; const next = !current;
    setOptimistic(v => ({ ...v, [key]: next })); setSaving(key); setMessage(null);
    try { await sprint27AdminApi.updatePreference(event.event_key, channel, next); setMessage({ ok: true, text: `${event.event_name} ${channel.replace("_", "-")} alerts ${next ? "enabled" : "disabled"}.` }); catalog.refetch(); }
    catch (error) { setOptimistic(v => { const copy = { ...v }; delete copy[key]; return copy; }); setMessage({ ok: false, text: error instanceof Error ? error.message : "Preference could not be saved." }); }
    finally { setSaving(null); }
  }
  if (catalog.loading) return <div className="nc-centered"><Spinner/></div>;
  if (catalog.error) return <EmptyState title="Preferences are unavailable" description={`${catalog.error}${catalog.requestId ? ` · ${catalog.requestId}` : ""}`} action={<Btn size="sm" onClick={catalog.refetch}>Retry</Btn>}/>;
  return <div className="nc-stack">
    <div className="nc-settings-hero"><div><span className="nc-eyebrow">PERSONAL DELIVERY CONTROL</span><h2>Administrator alert preferences</h2><p>Only events that can actually notify an administrator are listed. Mandatory alerts remain locked on.</p></div><div className="nc-health-chip"><strong>{liveChannels}</strong><span>of {providers.length} channels live</span></div></div>
    {message && <div className={`nc-message ${message.ok ? "success" : "danger"}`}>{message.text}</div>}
    <Card padding={0}><div className="nc-filterbar"><div className="nc-search"><Search size={15}/><Input placeholder="Search registered admin events" value={query} onChange={setQuery}/></div><Select value={source} onChange={setSource} options={[{ value: "", label: "All source engines" }, ...sources.map(v => ({ value: v, label: v.replace(/_/g, " ") }))]}/><div className="nc-legend"><span><i className="live"/>Available</span><span><i/>Unavailable</span><span><i className="locked"/>Mandatory</span></div></div>
      {events.length === 0 ? <EmptyState title="No matching admin events" description="Try another event name or source engine."/> : <div className="nc-pref-table-wrap"><TableSurface className="nc-table nc-pref-table"><thead><tr><th>Event</th>{providers.map(p => <th key={p.channel} className="center"><span>{p.channel.replace("_", "-")}</span><small className={p.configured ? "ok" : "off"}>{p.configured ? "LIVE" : "NOT CONNECTED"}</small></th>)}</tr></thead><tbody>{events.map(event => <tr key={event.event_key}><td><div className="nc-event-name">{event.event_name}{event.is_mandatory && <Badge variant="warning" size="sm">Mandatory</Badge>}</div><code>{event.event_key}</code><span className="nc-source">{event.source_engine.replace(/_/g, " ")}{event.vertical_key ? ` · ${event.vertical_key.replace(/_/g, " ")}` : " · global"}</span></td>{event.channels.map(channel => { const key = `${event.event_key}::${channel.channel}`; const on = key in optimistic ? optimistic[key] : channel.effective_enabled; const title = channel.locked_reason ?? `${event.event_name} via ${channel.channel}`; return <td key={channel.channel} className="center"><Toggle checked={on} disabled={!channel.configurable} busy={saving === key} label={title} onChange={() => toggle(event, channel.channel, on)}/><small className="nc-cell-note">{channel.configurable ? (channel.explicit_value === null ? "Platform default" : "Custom") : channel.locked_reason ?? channel.provider_state}</small></td>; })}</tr>)}</tbody></TableSurface></div>}
    </Card>
    <div className="nc-callout"><CircleAlert size={17}/><div><strong>Why most channels are unavailable</strong><p>Email, SMS, WhatsApp, and push are not connected to this outbox runtime. They are intentionally disabled so an administrator cannot save a preference the system cannot deliver.</p></div></div>
  </div>;
}

export default function NotificationCenterPage() {
  const [tab, setTabState] = useState<Tab>("feed"); const [status, setStatus] = useState(""); const [severity, setSeverity] = useState(""); const [type, setType] = useState(""); const [search, setSearch] = useState("");
  const debouncedSearch = useDebounced(search); const [page, setPage] = useState(1); const [selected, setSelected] = useState<InAppNotification | null>(null); const [toast, setToast] = useState<string | null>(null);
  useEffect(() => { const requested = new URLSearchParams(window.location.search).get("tab") as Tab | null; if (requested && TABS.some(t => t.key === requested)) setTabState(requested); }, []);
  function setTab(next: Tab) { setTabState(next); const url = new URL(window.location.href); url.searchParams.set("tab", next); window.history.replaceState({}, "", url); }
  useEffect(() => setPage(1), [status, severity, type, debouncedSearch]);
  const feed = useApi(useCallback(() => sprint27AdminApi.listNotifications({ read_status: status || undefined, notification_type: type || undefined, severity: severity || undefined, search: debouncedSearch || undefined, limit: PAGE_SIZE, offset: (page - 1) * PAGE_SIZE }), [status, severity, type, debouncedSearch, page]));
  const summary = useApi(useCallback(() => sprint27AdminApi.getNotificationSummary(), []), []);
  const markRead = useAction((id: string) => sprint27AdminApi.markRead(id)); const markAll = useAction(() => sprint27AdminApi.markAllRead());
  function notify(text: string) { setToast(text); setTimeout(() => setToast(null), 3200); }
  async function handleMarkRead(id: string) { const result = await markRead.execute(id); if (result) { feed.refetch(); summary.refetch(); notify("Notification marked as read."); } }
  async function handleMarkAll() { const result = await markAll.execute(); if (result) { feed.refetch(); summary.refetch(); notify(`${result.marked_read} notifications marked as read.`); } }
  const active = TABS.find(t => t.key === tab)!; const items = feed.data?.items ?? [];
  return <AdminLayout activeNav="notifications"><style>{`
    .nc-shell{--nc-soft:color-mix(in srgb,var(--brand) 7%,var(--surface));max-width:1680px;margin:0 auto}.nc-stack{display:flex;flex-direction:column;gap:16px}.nc-centered{min-height:240px;display:grid;place-items:center}.nc-eyebrow{font-size:10px;letter-spacing:.14em;font-weight:800;color:var(--brand)}
    .nc-tabs{display:flex;gap:6px;padding:6px;border:1px solid var(--border);background:var(--surface-sunken);border-radius:14px;overflow:auto;margin:4px 0 22px}.nc-tab{display:flex;align-items:center;gap:8px;white-space:nowrap;padding:10px 13px;border:1px solid transparent;border-radius:9px;background:transparent;color:var(--text-secondary);font:600 12px/1 inherit;cursor:pointer}.nc-tab:hover{color:var(--text-primary);background:var(--surface)}.nc-tab.active{color:var(--text-primary);background:var(--surface);border-color:var(--border);box-shadow:var(--shadow-sm)}
    .nc-context{display:flex;align-items:center;justify-content:space-between;gap:18px;margin:-10px 2px 18px}.nc-context p{margin:0;color:var(--text-tertiary);font-size:12px}.nc-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.nc-kpi{padding:17px 18px;border:1px solid var(--border);border-radius:13px;background:var(--surface);position:relative;overflow:hidden}.nc-kpi:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:var(--border-strong)}.nc-kpi.brand:before{background:var(--brand)}.nc-kpi.danger:before{background:var(--danger)}.nc-kpi strong{font-size:27px;line-height:1;color:var(--text-primary)}.nc-kpi span{display:block;margin-top:7px;font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:var(--text-tertiary);font-weight:700}
    .nc-filterbar{display:flex;align-items:center;gap:9px;padding:13px 14px;border-bottom:1px solid var(--border);flex-wrap:wrap}.nc-search{position:relative;display:flex;align-items:center;flex:1 1 260px}.nc-search>svg{position:absolute;left:11px;z-index:2;color:var(--text-tertiary)}.nc-search input{padding-left:34px!important}.nc-legend{display:flex;align-items:center;gap:12px;margin-left:auto;font-size:11px;color:var(--text-tertiary)}.nc-legend span{display:flex;align-items:center;gap:5px}.nc-legend i{width:7px;height:7px;border-radius:50%;background:var(--text-tertiary)}.nc-legend i.live{background:var(--success)}.nc-legend i.locked{background:var(--warning)}
    .nc-table{width:100%;border-collapse:collapse;font-size:12px}.nc-table th{padding:10px 14px;background:var(--surface-sunken);color:var(--text-tertiary);text-align:left;font-size:10px;letter-spacing:.06em;text-transform:uppercase;font-weight:800;border-bottom:1px solid var(--border)}.nc-table td{padding:12px 14px;border-bottom:1px solid var(--border);color:var(--text-secondary);vertical-align:middle}.nc-table tbody tr:last-child td{border-bottom:0}.nc-table tbody tr:hover{background:var(--surface-hover)}.nc-table .center{text-align:center}.nc-notif-title{font-weight:700;color:var(--text-primary);margin-bottom:3px}.nc-notif-body{max-width:560px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--text-secondary)}.nc-unread{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--brand);margin-right:8px}.nc-empty-error{padding:14px;color:var(--danger-text);font-size:12px}
    .nc-settings-hero{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:22px 24px;border:1px solid color-mix(in srgb,var(--brand) 24%,var(--border));border-radius:16px;background:linear-gradient(135deg,var(--nc-soft),var(--surface))}.nc-settings-hero h2{font-size:20px;margin:4px 0;color:var(--text-primary)}.nc-settings-hero p{font-size:12px;color:var(--text-secondary);margin:0}.nc-health-chip{display:flex;align-items:baseline;gap:7px;padding:11px 14px;background:var(--surface);border:1px solid var(--border);border-radius:10px;white-space:nowrap}.nc-health-chip strong{font-size:22px;color:var(--success-text)}.nc-health-chip span{font-size:11px;color:var(--text-tertiary)}.nc-message{padding:10px 13px;border-radius:9px;font-size:12px}.nc-message.success{background:var(--success-bg);border:1px solid var(--success-border);color:var(--success-text)}.nc-message.danger{background:var(--danger-bg);border:1px solid var(--danger-border);color:var(--danger-text)}
    .nc-pref-table-wrap{overflow:auto}.nc-pref-table th:first-child,.nc-pref-table td:first-child{min-width:340px}.nc-pref-table th:not(:first-child),.nc-pref-table td:not(:first-child){min-width:118px}.nc-pref-table th small{display:block;margin-top:3px;font-size:8px;letter-spacing:.05em}.nc-pref-table th small.ok{color:var(--success-text)}.nc-pref-table th small.off{color:var(--text-tertiary)}.nc-event-name{display:flex;align-items:center;gap:7px;font-weight:700;color:var(--text-primary);margin-bottom:4px}.nc-pref-table code{display:block;font-size:10px;color:var(--text-tertiary)}.nc-source{display:block;margin-top:4px;font-size:10px;color:var(--text-tertiary);text-transform:capitalize}.nc-cell-note{display:block;margin-top:5px;font-size:9px;color:var(--text-tertiary)}
    .nc-switch{width:40px;height:23px;padding:2px;border:0;border-radius:999px;background:var(--border-strong);cursor:pointer;transition:.16s;position:relative}.nc-switch span{display:block;width:19px;height:19px;border-radius:50%;background:white;box-shadow:0 1px 4px rgba(0,0,0,.25);transform:translateX(0);transition:.16s}.nc-switch[data-on=true]{background:var(--brand)}.nc-switch[data-on=true] span{transform:translateX(17px)}.nc-switch:disabled{cursor:not-allowed;opacity:.48}.nc-callout{display:flex;gap:11px;padding:14px 16px;border:1px solid var(--border);border-radius:12px;background:var(--surface-sunken);color:var(--text-secondary)}.nc-callout svg{color:var(--brand);flex:none}.nc-callout strong{font-size:12px;color:var(--text-primary)}.nc-callout p{font-size:11px;margin:3px 0 0;line-height:1.55}
    @media(max-width:980px){.nc-kpis{grid-template-columns:repeat(2,1fr)}.nc-settings-hero{align-items:flex-start}.nc-table .optional-col{display:none}}@media(max-width:620px){.nc-kpis{grid-template-columns:1fr 1fr}.nc-settings-hero{flex-direction:column}.nc-legend{width:100%;margin-left:0}.nc-context{align-items:flex-start;flex-direction:column}}
  `}</style><div className="nc-shell">
    <SectionHeader title="Notification Center" subtitle="Operate admin alerts, runtime templates, delivery policy, providers, and failure recovery from one workspace." actions={<Btn size="sm" variant="secondary" onClick={() => { feed.refetch(); summary.refetch(); }}><RefreshCw size={14}/> Refresh</Btn>}/>
    <nav className="nc-tabs" aria-label="Notification center sections">{TABS.map(item => <button key={item.key} className={`nc-tab ${tab === item.key ? "active" : ""}`} onClick={() => setTab(item.key)}>{item.icon}{item.label}</button>)}</nav>
    <div className="nc-context"><p>{active.description}</p>{tab === "feed" && <Btn size="sm" variant="secondary" onClick={handleMarkAll} loading={markAll.loading}><CheckCheck size={14}/> Mark all read</Btn>}</div>
    {tab === "templates" && <RuntimeTemplatesPanel/>}{tab === "policies" && <EventPoliciesPanel/>}{tab === "providers" && <DeliveryProvidersPanel/>}{tab === "payments" && <PaymentGatewayPanel/>}{tab === "storage" && <StorageConfigPanel/>}{tab === "logs" && <LogsFailuresPanel/>}{tab === "settings" && <NotificationSettingsPanel/>}
    {tab === "feed" && <div className="nc-stack">{toast && <div className="nc-message success">{toast}</div>}<div className="nc-kpis">{summary.loading ? Array.from({ length: 4 }, (_, i) => <Skeleton key={i} height={84}/>) : <><div className="nc-kpi"><strong>{summary.data?.total ?? 0}</strong><span>Total addressed</span></div><div className="nc-kpi brand"><strong>{summary.data?.unread ?? 0}</strong><span>Unread</span></div><div className="nc-kpi danger"><strong>{summary.data?.high_priority ?? 0}</strong><span>High priority</span></div><div className="nc-kpi"><strong>{summary.data?.read ?? 0}</strong><span>Reviewed</span></div></>}</div>
      <Card padding={0}><div className="nc-filterbar"><div className="nc-search"><Search size={15}/><Input placeholder="Search title or message" value={search} onChange={setSearch}/></div><Select value={status} onChange={setStatus} options={[{ value: "", label: "All states" }, { value: "unread", label: "Unread" }, { value: "read", label: "Read" }]}/><Select value={severity} onChange={setSeverity} options={[{ value: "", label: "All priorities" }, { value: "critical", label: "Critical" }, { value: "warning", label: "Warning" }, { value: "info", label: "Information" }, { value: "success", label: "Success" }]}/><Select value={type} onChange={setType} options={[{ value: "", label: "All event families" }, { value: "complaint.", label: "Complaints" }, { value: "review.", label: "Reviews" }, { value: "auth.", label: "Security" }, { value: "commission.", label: "Finance" }]}/>{(status || severity || type || search) && <Btn size="sm" variant="ghost" onClick={() => { setStatus(""); setSeverity(""); setType(""); setSearch(""); }}><SlidersHorizontal size={14}/> Clear</Btn>}</div>
        {feed.error ? <div className="nc-empty-error">{feed.error}{feed.requestId ? ` · ${feed.requestId}` : ""}</div> : feed.loading ? <div style={{ padding: 18 }}>{Array.from({ length: 6 }, (_, i) => <Skeleton key={i} height={52} style={{ marginBottom: 8 }}/>)}</div> : items.length === 0 ? <EmptyState title={feed.data?.total === 0 && !search && !status && !severity && !type ? "No admin alerts have been generated" : "No alerts match these filters"} description={feed.data?.total === 0 ? "The inbox is connected and ready. Admin-directed events will appear here when they occur." : "Clear or change the filters to widen the result set."} icon={<Bell size={36}/>}/> : <div style={{ overflowX: "auto" }}><TableSurface className="nc-table"><thead><tr><th>Notification</th><th>Event</th><th>Priority</th><th className="optional-col">Vertical</th><th>Created</th><th></th></tr></thead><tbody>{items.map(row => <tr key={row.id} onClick={() => setSelected(row)} style={{ cursor: "pointer" }}><td><div className="nc-notif-title">{row.read_status === "unread" && <span className="nc-unread"/>}{row.title}</div><div className="nc-notif-body">{row.body}</div></td><td><Badge variant="muted">{row.notification_type.replace(/_/g, " ")}</Badge></td><td><Badge variant={SEVERITY_VARIANT[row.severity] ?? "muted"}>{row.severity}</Badge></td><td className="optional-col">{row.vertical_key?.replace(/_/g, " ") ?? "Global"}</td><td>{new Date(row.created_at).toLocaleString()}</td><td onClick={e => e.stopPropagation()}><Btn size="xs" variant="ghost" onClick={() => setSelected(row)}><Eye size={13}/></Btn>{row.read_status === "unread" && <Btn size="xs" variant="secondary" onClick={() => handleMarkRead(row.id)}>Read</Btn>}</td></tr>)}</tbody></TableSurface></div>}<Pagination page={page} total={feed.data?.total ?? 0} pageSize={PAGE_SIZE} onPage={setPage}/>
      </Card></div>}
    {selected && <Modal open onClose={() => setSelected(null)} title={selected.title} size="md"><div className="nc-stack"><div style={{ display: "flex", gap: 7 }}><Badge variant={SEVERITY_VARIANT[selected.severity] ?? "muted"}>{selected.severity}</Badge><Badge variant={selected.read_status === "unread" ? "warning" : "success"}>{selected.read_status}</Badge>{selected.is_mandatory && <Badge variant="warning">Mandatory</Badge>}</div><div className="nc-callout"><Bell size={17}/><div><strong>{selected.notification_type}</strong><p>{selected.body}</p></div></div><div style={{ fontSize: 12, color: "var(--text-secondary)" }}><strong>Created:</strong> {new Date(selected.created_at).toLocaleString()}<br/><strong>Scope:</strong> {selected.vertical_key ?? "Global"}{selected.source_record_type ? <><br/><strong>Related:</strong> {selected.source_record_type} · {selected.source_record_id}</> : null}</div><div style={{ display: "flex", justifyContent: "flex-end", gap: 8 }}>{selected.action_url && <Link href={selected.action_url}><Btn size="sm">{selected.action_label ?? "Open record"}</Btn></Link>}{selected.read_status === "unread" && <Btn size="sm" variant="secondary" onClick={() => handleMarkRead(selected.id)}>Mark read</Btn>}<Btn size="sm" variant="ghost" onClick={() => setSelected(null)}>Close</Btn></div></div></Modal>}
  </div></AdminLayout>;
}
