"""Default platform notification templates seeded for the Template Center.

Wording rule (Home Services direct-pay model): use "Pay the remaining amount
directly to the provider" — never "platform payment received"/"provider
payout initiated"/"wallet cash deducted" (usage credits are internal platform
credits, not real money; see Trust & Quality / Tenant 360 business rules).
"""

DEFAULT_TEMPLATE_SPECS: list[dict] = [
    {"event_type": "booking_confirmed", "audience": "customer", "app_scope": "customer_app",
     "title": "Booking Confirmed", "subject": "Your booking is confirmed",
     "body": "Hi {{customer_name}}, your booking {{booking_number}} for {{service_name}} with {{provider_name}} is confirmed for {{scheduled_time}}.",
     "variables": ["customer_name", "booking_number", "service_name", "provider_name", "scheduled_time"]},
    {"event_type": "booking_cancelled", "audience": "customer", "app_scope": "customer_app",
     "title": "Booking Cancelled", "subject": "Your booking was cancelled",
     "body": "Hi {{customer_name}}, your booking {{booking_number}} for {{service_name}} has been cancelled.",
     "variables": ["customer_name", "booking_number", "service_name"]},
    {"event_type": "booking_rescheduled", "audience": "customer", "app_scope": "customer_app",
     "title": "Booking Rescheduled", "subject": "Your booking time has changed",
     "body": "Hi {{customer_name}}, your booking {{booking_number}} has been rescheduled to {{scheduled_time}}.",
     "variables": ["customer_name", "booking_number", "scheduled_time"]},
    {"event_type": "provider_assigned", "audience": "customer", "app_scope": "customer_app",
     "title": "Provider Assigned", "subject": "A provider has been assigned to your booking",
     "body": "Hi {{customer_name}}, {{provider_name}} has been assigned to your booking {{booking_number}}.",
     "variables": ["customer_name", "provider_name", "booking_number"]},
    {"event_type": "job_assigned", "audience": "technician", "app_scope": "staff_app",
     "title": "New Job Assigned", "subject": "You have a new job",
     "body": "Job {{job_number}} has been assigned to you. Please arrive by {{arrival_time}}.",
     "variables": ["job_number", "arrival_time"]},
    {"event_type": "job_status_changed", "audience": "customer", "app_scope": "customer_app",
     "title": "Job Status Updated", "subject": "Your job status has changed",
     "body": "Hi {{customer_name}}, your job {{job_number}} is now {{job_status}}.",
     "variables": ["customer_name", "job_number", "job_status"]},
    {"event_type": "payment_recorded", "audience": "customer", "app_scope": "customer_app",
     "title": "Payment Recorded", "subject": "Payment recorded for your job",
     "body": "Hi {{customer_name}}, your payment for job {{job_number}} has been recorded. Pay the remaining amount directly to the provider if applicable.",
     "variables": ["customer_name", "job_number"]},
    {"event_type": "review_requested", "audience": "customer", "app_scope": "customer_app",
     "title": "How was your service?", "subject": "Rate your recent service",
     "body": "Hi {{customer_name}}, please rate your experience with {{provider_name}} for booking {{booking_number}}.",
     "variables": ["customer_name", "provider_name", "booking_number"]},
    {"event_type": "complaint_created", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "New Complaint Received", "subject": "A new complaint has been filed",
     "body": "A complaint was filed for booking {{booking_number}}. Please review it in your dashboard.",
     "variables": ["booking_number"]},
    {"event_type": "dispute_created", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "New Dispute Opened", "subject": "A dispute has been opened",
     "body": "A dispute was opened for job {{job_number}}. Please review it in your dashboard.",
     "variables": ["job_number"]},
    {"event_type": "customer_service_credit_issued", "audience": "customer", "app_scope": "customer_app",
     "title": "ServiceOS Credit Issued", "subject": "You've received a service credit",
     "body": "Hi {{customer_name}}, you've been issued {{customer_service_credit_amount}} in ServiceOS credit.",
     "variables": ["customer_name", "customer_service_credit_amount"]},
    {"event_type": "tenant_approved", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Provider Application Approved", "subject": "You're approved on ServiceOS",
     "body": "Congratulations {{tenant_name}}, your application has been approved. Package: {{package_name}}.",
     "variables": ["tenant_name", "package_name"]},
    {"event_type": "tenant_changes_requested", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Changes Requested", "subject": "Action needed on your application",
     "body": "Hi {{tenant_name}}, changes are needed: {{change_request_reason}}.",
     "variables": ["tenant_name", "change_request_reason"]},
    {"event_type": "staff_invited", "audience": "tenant_staff", "app_scope": "staff_app",
     "title": "You've Been Invited", "subject": "You've been invited to join a team",
     "body": "You've been invited to join {{tenant_name}} on ServiceOS.",
     "variables": ["tenant_name"]},
    {"event_type": "package_expiring", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Package Expiring Soon", "subject": "Your package is expiring soon",
     "body": "Hi {{tenant_name}}, your package {{package_name}} is expiring soon. Renew to avoid interruption.",
     "variables": ["tenant_name", "package_name"]},
    {"event_type": "usage_credit_low", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Usage Credits Running Low", "subject": "Your usage credit balance is low",
     "body": "Hi {{tenant_name}}, your usage credit balance is {{usage_credit_balance}}. Top up to keep receiving bookings.",
     "variables": ["tenant_name", "usage_credit_balance"]},
    {"event_type": "security_deposit_required", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Security Deposit Required", "subject": "Security deposit required",
     "body": "Hi {{tenant_name}}, a security deposit of {{security_deposit_amount}} is required to continue.",
     "variables": ["tenant_name", "security_deposit_amount"]},
    {"event_type": "document_expiring", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Document Expiring", "subject": "One of your documents is expiring",
     "body": "Hi {{tenant_name}}, one of your verification documents is expiring soon. Please renew it.",
     "variables": ["tenant_name"]},
    {"event_type": "login_otp", "audience": "customer", "app_scope": "customer_app",
     "title": "Your Login Code", "subject": "Your ServiceOS login code",
     "body": "Hi {{customer_name}}, use this code to log in. Do not share it with anyone.",
     "variables": ["customer_name"]},
    {"event_type": "password_reset", "audience": "customer", "app_scope": "customer_app",
     "title": "Password Reset Requested", "subject": "Reset your password",
     "body": "Hi {{customer_name}}, we received a request to reset your password.",
     "variables": ["customer_name"]},
]
