"""Default platform notification templates seeded for the Template Center.

Wording rule (Home Services direct-pay model): use "Pay the remaining amount
directly to the provider" — never "platform payment received"/"provider
payout initiated"/"wallet cash deducted" (usage credits are internal platform
credits, not real money; see Trust & Quality / Tenant 360 business rules).
"""

DEFAULT_TEMPLATE_SPECS: list[dict] = [
    {"event_type": "booking_confirmed", "audience": "customer", "app_scope": "customer_app",
     "title": "Booking Confirmed", "subject": "Your booking is confirmed",
     "body": "Hi {{customer_name}}, your booking {{booking_number}} for {{service_name}} with {{provider_name}} is confirmed for {{scheduled_time}}.",
     "variables": ["customer_name", "booking_number", "service_name", "provider_name", "scheduled_time"]},
    {"event_type": "booking_cancelled", "audience": "customer", "app_scope": "customer_app",
     "title": "Booking Cancelled", "subject": "Your booking was cancelled",
     "body": "Hi {{customer_name}}, your booking {{booking_number}} for {{service_name}} has been cancelled.",
     "variables": ["customer_name", "booking_number", "service_name"]},
    {"event_type": "booking_rescheduled", "audience": "customer", "app_scope": "customer_app",
     "title": "Booking Rescheduled", "subject": "Your booking time has changed",
     "body": "Hi {{customer_name}}, your booking {{booking_number}} has been rescheduled to {{scheduled_time}}.",
     "variables": ["customer_name", "booking_number", "scheduled_time"]},
    {"event_type": "provider_assigned", "audience": "customer", "app_scope": "customer_app",
     "title": "Provider Assigned", "subject": "A provider has been assigned to your booking",
     "body": "Hi {{customer_name}}, {{provider_name}} has been assigned to your booking {{booking_number}}.",
     "variables": ["customer_name", "provider_name", "booking_number"]},
    {"event_type": "job_assigned", "audience": "technician", "app_scope": "staff_app",
     "title": "New Job Assigned", "subject": "You have a new job",
     "body": "Job {{job_number}} has been assigned to you. Please arrive by {{arrival_time}}.",
     "variables": ["job_number", "arrival_time"]},
    {"event_type": "job_status_changed", "audience": "customer", "app_scope": "customer_app",
     "title": "Job Status Updated", "subject": "Your job status has changed",
     "body": "Hi {{customer_name}}, your job {{job_number}} is now {{job_status}}.",
     "variables": ["customer_name", "job_number", "job_status"]},
    {"event_type": "payment_recorded", "audience": "customer", "app_scope": "customer_app",
     "title": "Payment Recorded", "subject": "Payment recorded for your job",
     "body": "Hi {{customer_name}}, your payment for job {{job_number}} has been recorded. Pay the remaining amount directly to the provider if applicable.",
     "variables": ["customer_name", "job_number"]},
    {"event_type": "review_requested", "audience": "customer", "app_scope": "customer_app",
     "title": "How was your service?", "subject": "Rate your recent service",
     "body": "Hi {{customer_name}}, please rate your experience with {{provider_name}} for booking {{booking_number}}.",
     "variables": ["customer_name", "provider_name", "booking_number"]},
    {"event_type": "complaint_created", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "New Complaint Received", "subject": "A new complaint has been filed",
     "body": "A complaint was filed for booking {{booking_number}}. Please review it in your dashboard.",
     "variables": ["booking_number"]},
    {"event_type": "dispute_created", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "New Dispute Opened", "subject": "A dispute has been opened",
     "body": "A dispute was opened for job {{job_number}}. Please review it in your dashboard.",
     "variables": ["job_number"]},
    {"event_type": "customer_service_credit_issued", "audience": "customer", "app_scope": "customer_app",
     "title": "Fuvay Credit Issued", "subject": "You've received a service credit",
     "body": "Hi {{customer_name}}, you've been issued {{customer_service_credit_amount}} in Fuvay credit.",
     "variables": ["customer_name", "customer_service_credit_amount"]},
    {"event_type": "tenant_approved", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Provider Application Approved", "subject": "You're approved on Fuvay",
     "body": "Congratulations {{tenant_name}}, your application has been approved. Package: {{package_name}}.",
     "variables": ["tenant_name", "package_name"]},
    {"event_type": "tenant_changes_requested", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Changes Requested", "subject": "Action needed on your application",
     "body": "Hi {{tenant_name}}, changes are needed: {{change_request_reason}}.",
     "variables": ["tenant_name", "change_request_reason"]},
    {"event_type": "staff_invited", "audience": "tenant_staff", "app_scope": "staff_app",
     "title": "You've Been Invited", "subject": "You've been invited to join a team",
     "body": "You've been invited to join {{tenant_name}} on Fuvay.",
     "variables": ["tenant_name"]},
    {"event_type": "package_expiring", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Package Expiring Soon", "subject": "Your package is expiring soon",
     "body": "Hi {{tenant_name}}, your package {{package_name}} is expiring soon. Renew to avoid interruption.",
     "variables": ["tenant_name", "package_name"]},
    {"event_type": "usage_credit_low", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Usage Credits Running Low", "subject": "Your usage credit balance is low",
     "body": "Hi {{tenant_name}}, your usage credit balance is {{usage_credit_balance}}. Top up to keep receiving bookings.",
     "variables": ["tenant_name", "usage_credit_balance"]},
    {"event_type": "document_expiring", "audience": "tenant_owner", "app_scope": "tenant_app",
     "title": "Document Expiring", "subject": "One of your documents is expiring",
     "body": "Hi {{tenant_name}}, one of your verification documents is expiring soon. Please renew it.",
     "variables": ["tenant_name"]},
    {"event_type": "login_otp", "audience": "customer", "app_scope": "customer_app",
     "title": "Your Login Code", "subject": "Your Fuvay login code",
     "body": "Hi {{customer_name}}, use this code to log in. Do not share it with anyone.",
     "variables": ["customer_name"]},
    {"event_type": "password_reset", "audience": "customer", "app_scope": "customer_app",
     "title": "Password Reset Requested", "subject": "Reset your password",
     "body": "Hi {{customer_name}}, we received a request to reset your password.",
     "variables": ["customer_name"]},
]

# Operational customer copy used by the Instagram booking and field-service
# lifecycle.  These are intentionally platform defaults: a tenant/vertical
# override can be added later without changing code or losing the fallback.
OPERATIONAL_TEMPLATE_SPECS: list[dict] = [
    {"event_type": "customer_technician_assigned", "title": "Your technician", "body": "Technician assigned\nBooking: {{booking_number}}\n{{technician_name}} has been assigned. Visit: {{visit_label}}.\n\nਟੈਕਨੀਸ਼ੀਅਨ assign ਹੋ ਗਿਆ ਹੈ\nBooking: {{booking_number}}\n{{technician_name}} ਤੁਹਾਡੀ service ਲਈ assign ਹੋ ਗਏ ਹਨ। Visit: {{visit_label}}.", "variables": ["booking_number", "technician_name", "visit_label"]},
    {"event_type": "customer_technician_on_the_way", "title": "Your technician", "body": "Technician on the way\n{{technician_name}} is travelling to your service location now. Visit: {{visit_label}}.\n\nਟੈਕਨੀਸ਼ੀਅਨ ਰਸਤੇ ਵਿੱਚ ਹੈ\n{{technician_name}} ਹੁਣ ਤੁਹਾਡੇ service location ਵੱਲ ਆ ਰਹੇ ਹਨ।", "variables": ["technician_name", "visit_label"]},
    {"event_type": "customer_technician_arrived", "title": "Your technician", "body": "Arrival update\n{{technician_name}} has arrived for your visit.\n\nਪਹੁੰਚ ਅਪਡੇਟ\n{{technician_name}} ਤੁਹਾਡੀ service location 'ਤੇ ਪਹੁੰਚ ਗਏ ਹਨ।", "variables": ["technician_name", "visit_label"]},
    {"event_type": "customer_arrival_confirmation_requested", "title": "Confirm arrival", "body": "Confirm technician arrival\n{{technician_name}} says they are at your service location. Confirm only after you can see them. Arrival code: {{arrival_code}}. It expires in {{expiry_minutes}} minutes. Never share this code over a phone call.\n\nਟੈਕਨੀਸ਼ੀਅਨ ਦੀ ਪਹੁੰਚ confirm ਕਰੋ\nਸਾਹਮਣੇ ਵੇਖਣ ਤੋਂ ਬਾਅਦ ਹੀ confirm ਕਰੋ। Arrival code: {{arrival_code}}। ਇਹ {{expiry_minutes}} ਮਿੰਟ ਵਿੱਚ expire ਹੋਵੇਗਾ।", "variables": ["technician_name", "arrival_code", "expiry_minutes"], "action_label": "Yes, arrived"},
    {"event_type": "customer_arrival_confirmed", "title": "Arrival verified", "body": "Arrival verified. The technician can now begin inspection or the approved service.\n\nਪਹੁੰਚ verify ਹੋ ਗਈ ਹੈ। ਟੈਕਨੀਸ਼ੀਅਨ ਹੁਣ inspection ਜਾਂ approved service ਸ਼ੁਰੂ ਕਰ ਸਕਦਾ ਹੈ।", "variables": []},
    {"event_type": "customer_reschedule_approval_requested", "title": "Visit slot approval", "body": "Reschedule approval needed\nBooking: {{booking_number}}\nCurrent: {{current_slot}}\nRequested: {{requested_slot}}\nReason: {{reason}}\nYour current slot remains confirmed unless you approve. This request expires {{expires_at}}.\n\nਨਵਾਂ slot approve ਕਰਨਾ ਲਾਜ਼ਮੀ ਹੈ\nਤੁਹਾਡੀ approval ਤੋਂ ਬਿਨਾਂ ਮੌਜੂਦਾ slot ਹੀ confirmed ਰਹੇਗਾ।", "variables": ["booking_number", "current_slot", "requested_slot", "reason", "expires_at"], "action_label": "Approve new slot"},
    {"event_type": "customer_provider_cancellation_confirmation_requested", "title": "Confirm cancellation", "body": "Confirm cancellation request\nBooking: {{booking_number}}\nReason: {{reason}}\nConfirm only if you asked to cancel. Your booking and SLA remain active until you confirm. This request expires {{expires_at}}.\n\nCancellation request confirm ਕਰੋ\nਸਿਰਫ਼ ਉਦੋਂ confirm ਕਰੋ ਜੇ cancellation ਤੁਸੀਂ ਮੰਗੀ ਸੀ।", "variables": ["booking_number", "reason", "expires_at"], "action_label": "Yes, cancel"},
    {"event_type": "customer_stage_scheduled", "title": "Visit scheduled", "body": "Your visit schedule has been updated.\n\nਤੁਹਾਡੀ visit ਦਾ schedule update ਹੋ ਗਿਆ ਹੈ।", "variables": []},
    {"event_type": "customer_stage_inspection_started", "title": "Inspection started", "body": "The technician has started the inspection. We will message you before any quoted work begins.\n\nਟੈਕਨੀਸ਼ੀਅਨ ਨੇ inspection ਸ਼ੁਰੂ ਕਰ ਦਿੱਤੀ ਹੈ। Quote ਵਾਲਾ ਕੰਮ ਸ਼ੁਰੂ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਤੁਹਾਡੀ approval ਲਵਾਂਗੇ।", "variables": []},
    {"event_type": "customer_stage_inspection_done", "title": "Inspection complete", "body": "The inspection is complete. If an estimate is required, approve it here before work begins.\n\nInspection ਪੂਰੀ ਹੋ ਗਈ ਹੈ। ਜੇ estimate ਲੋੜੀਂਦਾ ਹੋਇਆ ਤਾਂ ਕੰਮ ਤੋਂ ਪਹਿਲਾਂ ਇੱਥੇ approve ਕਰੋ।", "variables": []},
    {"event_type": "customer_stage_quote_required", "title": "Approval required", "body": "The technician is preparing an estimate or parts request. Work cannot continue without the required approval.\n\nਟੈਕਨੀਸ਼ੀਅਨ estimate ਜਾਂ parts request ਤਿਆਰ ਕਰ ਰਿਹਾ ਹੈ। ਤੁਹਾਡੀ approval ਤੋਂ ਬਿਨਾਂ ਕੰਮ ਅੱਗੇ ਨਹੀਂ ਵਧੇਗਾ।", "variables": []},
    {"event_type": "customer_stage_service_started", "title": "Work started", "body": "The approved service work has started.\n\nApproved service ਦਾ ਕੰਮ ਸ਼ੁਰੂ ਹੋ ਗਿਆ ਹੈ।", "variables": []},
    {"event_type": "customer_stage_work_done", "title": "Work marked done", "body": "The technician marked the work as done. Review the completion proof, handover and payment request before closure.\n\nਟੈਕਨੀਸ਼ੀਅਨ ਨੇ ਕੰਮ complete mark ਕੀਤਾ ਹੈ। Job close ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ proof, handover ਅਤੇ payment check ਕਰੋ।", "variables": []},
    {"event_type": "customer_stage_customer_not_available", "title": "Customer unavailable", "body": "The technician reported that the customer was unavailable. Contact the provider to reschedule or resolve the visit.\n\nਟੈਕਨੀਸ਼ੀਅਨ ਨੇ customer unavailable report ਕੀਤਾ ਹੈ। Visit resolve ਕਰਨ ਲਈ provider ਨਾਲ ਸੰਪਰਕ ਕਰੋ।", "variables": []},
    {"event_type": "customer_stage_delay_action_required", "title": "Your action is needed", "body": "Action needed\nBooking {{job_number}} is waiting for your confirmation at the {{stage_label}} step. Please complete the pending approval in this chat.\n\nਤੁਹਾਡੀ ਕਾਰਵਾਈ ਲੋੜੀਂਦੀ ਹੈ\nBooking {{job_number}} {{stage_label}} step 'ਤੇ ਤੁਹਾਡੀ confirmation ਦੀ ਉਡੀਕ ਕਰ ਰਹੀ ਹੈ।", "variables": ["job_number", "stage_label"]},
    {"event_type": "customer_stage_delay_critical", "title": "Service delay update", "body": "Service delay\nBooking {{job_number}} is delayed at the {{stage_label}} step. We have sent the provider an urgent action alert.\n\nService ਵਿੱਚ ਦੇਰੀ\nProvider ਨੂੰ urgent action ਲਈ alert ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ।", "variables": ["job_number", "stage_label"]},
    {"event_type": "customer_stage_delay_warning", "title": "Service status update", "body": "Service status\nBooking {{job_number}} has not progressed from {{stage_label}}. The provider has been alerted.\n\nService status\nProvider ਨੂੰ alert ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ।", "variables": ["job_number", "stage_label"]},
    {"event_type": "customer_handover_requested", "title": "Service handover", "body": "The technician marked the work complete. Check the work and confirm handover only when you are satisfied.\n\nਟੈਕਨੀਸ਼ੀਅਨ ਨੇ ਕੰਮ complete mark ਕੀਤਾ ਹੈ। ਕੰਮ check ਕਰਕੇ ਹੀ handover confirm ਕਰੋ।", "variables": ["job_number"], "action_label": "Confirm handover"},
    {"event_type": "customer_handover_reminder", "title": "Service handover reminder", "body": "Reminder: please check the completed work and confirm handover.\n\nਯਾਦ ਦਿਵਾਉਣਾ: ਕੰਮ check ਕਰਕੇ handover confirm ਕਰੋ।", "variables": ["job_number"], "action_label": "Confirm handover"},
    {"event_type": "customer_payment_requested", "title": "Direct payment", "body": "Direct payment recorded\nAmount: {{amount}}\nThe provider recorded this payment as received directly. Fuvay did not collect this money.\n\nDirect payment ਦਰਜ ਹੋਈ\nਰਕਮ: {{amount}}\nProvider ਨੇ ਇਹ payment ਸਿੱਧੀ ਮਿਲੀ ਦਰਜ ਕੀਤੀ ਹੈ।", "variables": ["job_number", "amount"], "action_label": "Yes, paid"},
    {"event_type": "customer_payment_reminder", "title": "Direct payment reminder", "body": "Reminder: confirm whether the direct payment of {{amount}} was made to the provider.\n\nਯਾਦ ਦਿਵਾਉਣਾ: provider ਨੂੰ {{amount}} payment ਹੋਣ ਦੀ confirmation ਦਿਓ।", "variables": ["job_number", "amount"], "action_label": "Yes, paid"},
    {"event_type": "customer_provider_cancelled", "title": "Booking cancelled", "body": "Booking cancelled\nBooking: {{booking_number}}\nReason: {{reason}}\nThe provider cancelled this booking. We are sorry for the inconvenience. You can choose another slot below.\n\nBooking cancel ਹੋ ਗਈ\nਕਾਰਨ: {{reason}}\nਅਸੁਵਿਧਾ ਲਈ ਸਾਨੂੰ ਅਫਸੋਸ ਹੈ।", "variables": ["booking_number", "reason"], "action_label": "Book again"},
    {"event_type": "customer_technician_unavailable_cancelled", "title": "Booking cancelled", "body": "Booking cancelled\nBooking: {{booking_number}}\nThe assigned technician is unavailable. We are sorry for the inconvenience.\n\nBooking cancel ਹੋ ਗਈ\nAssigned technician available ਨਹੀਂ ਹੈ।", "variables": ["booking_number"], "action_label": "Book again"},
    {"event_type": "customer_sla_cancelled", "title": "Booking cancelled", "body": "Booking cancelled\nBooking: {{booking_number}}\nThe technician did not arrive within the service deadline. We are sorry for the inconvenience.\n\nBooking cancel ਹੋ ਗਈ\nਟੈਕਨੀਸ਼ੀਅਨ service deadline ਅੰਦਰ ਨਹੀਂ ਪਹੁੰਚਿਆ।", "variables": ["booking_number"], "action_label": "Book again"},
    {"event_type": "customer_visit_reminder", "title": "Visit reminder", "body": "Visit reminder\n{{technician_name}} is scheduled to visit you {{visit_label}}.\n\nVisit reminder\n{{technician_name}} ਦੀ ਤੁਹਾਡੇ ਕੋਲ visit {{visit_label}} ਲਈ scheduled ਹੈ।", "variables": ["job_number", "technician_name", "visit_label"]},
    {"event_type": "customer_assignment_cancelled", "title": "Booking cancelled", "body": "Booking cancelled\nBooking: {{booking_number}}\nThe provider did not assign a technician within the required time, and no available provider could take the job. We are sorry for the inconvenience. Reply /human for help.\n\nBooking cancel ਹੋ ਗਈ\nProvider ਨੇ required time ਵਿੱਚ technician assign ਨਹੀਂ ਕੀਤਾ। ਮਦਦ ਲਈ /human ਲਿਖੋ।", "variables": ["booking_number"]},
]

for _spec in OPERATIONAL_TEMPLATE_SPECS:
    _spec.update({
        "audience": "customer",
        "app_scope": "customer_app",
        "channels": ["instagram"],
        "vertical_key": "home_services",
    })

DEFAULT_TEMPLATE_SPECS.extend(OPERATIONAL_TEMPLATE_SPECS)
