/**
 * Machine-readable customer capability registry -- Phase D's central
 * deliverable. Every entry's `evidence` classification is backed by one
 * of two things gathered THIS phase, never by prior documentation or the
 * deleted historical customer app:
 *
 *  1. Live OpenAPI schema introspection of the actual running FastAPI
 *     app (`app.openapi()["paths"]`, produced directly from real
 *     `@router` decorators -- this is the app's own runtime route table,
 *     not a doc) -- 210 `/customer`-scoped paths were enumerated this
 *     phase from a clean run of `app.main:app`.
 *  2. Direct reads of the router/service/model source files named in
 *     each entry's `blocker`/comment.
 *
 * No entry here was exercised with a live authenticated HTTP request
 * against a running server + database this phase -- that is why nothing
 * is classified RUNTIME_PROVEN. The strongest tier reached is
 * SOURCE_VERIFIED, and only where the underlying router/model file was
 * actually opened and read (not just the path listed).
 *
 * See CAPABILITY_MATRIX.md in this folder for the human-readable version
 * of this same evidence.
 */
import { CustomerCapability } from "./types";

export const CUSTOMER_CAPABILITY_REGISTRY: CustomerCapability[] = [
  // ── Application bootstrap ────────────────────────────────────────────
  {
    key: "appConfig.runtimeConfig", group: "Application bootstrap", label: "Runtime configuration",
    vertical: "global", evidence: "MISSING", requiresAuth: false,
    canonicalEndpoint: null, canonicalDataModel: null, offlinePolicy: "NOT_APPLICABLE",
    blocker: "No customer-facing bootstrap/runtime-config endpoint exists anywhere in the OpenAPI schema (2409 paths enumerated). Feature flags exist only tenant/admin-scoped (/v1/tenants/{id}/feature-flags, /v1/admin/settings/feature-flags).",
    verificationSource: "live_openapi_introspection", exposableInUi: false,
  },
  {
    key: "appConfig.enabledVerticals", group: "Application bootstrap", label: "Enabled verticals",
    vertical: "global", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/categories", canonicalDataModel: "catalog category/offering",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "No dedicated 'enabled verticals for me' endpoint. Vertical availability must be INFERRED from which categories/offerings the categories endpoint actually returns -- see domain/catalog.ts adaptCategory, which hides any vertical string it doesn't recognize rather than guessing.",
    verificationSource: "live_openapi_introspection", exposableInUi: true,
  },
  { key: "appConfig.featureFlags", group: "Application bootstrap", label: "Feature flags",
    vertical: "global", evidence: "MISSING", requiresAuth: false, canonicalEndpoint: null, canonicalDataModel: null,
    offlinePolicy: "NOT_APPLICABLE", blocker: "Only tenant/admin-scoped feature-flag routes exist.",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "appConfig.maintenanceState", group: "Application bootstrap", label: "Maintenance state",
    vertical: "global", evidence: "MISSING", requiresAuth: false, canonicalEndpoint: null, canonicalDataModel: null,
    offlinePolicy: "NOT_APPLICABLE", blocker: "No maintenance-mode endpoint found in the OpenAPI schema.",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "appConfig.minSupportedVersion", group: "Application bootstrap", label: "Minimum supported app version",
    vertical: "global", evidence: "MISSING", requiresAuth: false, canonicalEndpoint: null, canonicalDataModel: null,
    offlinePolicy: "NOT_APPLICABLE", blocker: "No min-version/force-update endpoint found.",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "appConfig.globalServiceAvailability", group: "Application bootstrap", label: "Global service availability",
    vertical: "global", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/home-services/booking-drafts/{draft_id}/serviceability-check",
    canonicalDataModel: "serviceability check result", offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "Availability is checked per-draft/per-zipcode, not as a standalone global-status read.",
    verificationSource: "live_openapi_introspection", exposableInUi: true },

  // ── Authentication and session (types only, per Phase D section 7) ──
  { key: "auth.otpRequest", group: "Authentication and session", label: "Phone OTP request",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: false, canonicalEndpoint: "/v1/auth/otp/send",
    canonicalDataModel: "auth session", offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "Route confirmed mounted; not a customer-exclusive route (generic auth engine) -- transport not implemented this phase (types only, per spec).",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "auth.otpVerify", group: "Authentication and session", label: "Phone OTP verification",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: false, canonicalEndpoint: "/v1/auth/otp/verify",
    canonicalDataModel: "auth session", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "auth.emailPasswordLogin", group: "Authentication and session", label: "Email/password login fallback",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: false, canonicalEndpoint: "/v1/auth/login",
    canonicalDataModel: "auth session", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "auth.refreshSession", group: "Authentication and session", label: "Refresh session",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/auth/token/refresh",
    canonicalDataModel: "auth session", offlinePolicy: "IDEMPOTENT_MUTATION",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "auth.logout", group: "Authentication and session", label: "Logout",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/auth/logout",
    canonicalDataModel: "auth session", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "auth.trustedDevice", group: "Authentication and session", label: "Trusted device",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/auth/me/devices/{session_id}/remove-trust", canonicalDataModel: "auth session",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "auth.mfaChallenge", group: "Authentication and session", label: "MFA challenge",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/auth/mfa/verify",
    canonicalDataModel: "auth session", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "auth.sessionExpiry", group: "Authentication and session", label: "Session expiry",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/auth/access-context",
    canonicalDataModel: "auth session", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "auth.suspendedAccount", group: "Authentication and session", label: "Suspended account",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/auth/access-context",
    canonicalDataModel: "auth session", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "auth.roleAudienceValidation", group: "Authentication and session", label: "Customer role/audience validation",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/auth/access-context",
    canonicalDataModel: "auth session", offlinePolicy: "NOT_APPLICABLE",
    blocker: "Phase E must reject any non-'serviceos:customer' audience token -- see domain/auth.ts CustomerSessionContext.",
    verificationSource: "live_openapi_introspection", exposableInUi: false },

  // ── Customer profile ─────────────────────────────────────────────────
  { key: "profile.read", group: "Customer profile", label: "Read profile",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/customer/profile",
    canonicalDataModel: "customer profile", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "profile.update", group: "Customer profile", label: "Update profile",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/customer/profile",
    canonicalDataModel: "customer profile", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "profile.photo", group: "Customer profile", label: "Profile photo",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/customer/profile/photo",
    canonicalDataModel: "customer profile", offlinePolicy: "MEDIA_UPLOAD",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "profile.consentState", group: "Customer profile", label: "Consent state",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/me/privacy/consents",
    canonicalDataModel: "consent record", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "profile.accountStatus", group: "Customer profile", label: "Account status",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/customer/profile",
    canonicalDataModel: "customer profile", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "live_openapi_introspection", exposableInUi: true },

  // ── Addresses ─────────────────────────────────────────────────────────
  { key: "addresses.list", group: "Addresses", label: "List addresses",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/customers/me/addresses",
    canonicalDataModel: "customer address", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "addresses.create", group: "Addresses", label: "Create address",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/customers/me/addresses",
    canonicalDataModel: "customer address", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "addresses.update", group: "Addresses", label: "Update address",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customers/me/addresses/{address_id}", canonicalDataModel: "customer address",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "addresses.delete", group: "Addresses", label: "Delete address",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customers/me/addresses/{address_id}", canonicalDataModel: "customer address",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "addresses.setDefault", group: "Addresses", label: "Set default",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customers/me/addresses/{address_id}/set-default", canonicalDataModel: "customer address",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "addresses.bookingSnapshot", group: "Addresses", label: "Booking-address snapshot",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/home-services/booking-drafts/{draft_id}",
    canonicalDataModel: "ServiceBooking.address_snapshot", offlinePolicy: "NOT_APPLICABLE",
    blocker: "Confirmed via app/engines/final_records/models.py ServiceBooking.address_snapshot (JSONB) -- snapshotted at confirm time, immutable after.",
    verificationSource: "model_source_read", exposableInUi: true },
  { key: "addresses.serviceabilityValidation", group: "Addresses", label: "Zipcode/serviceability validation",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/home-services/booking-drafts/{draft_id}/serviceability-check",
    canonicalDataModel: "serviceability result", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "live_openapi_introspection", exposableInUi: true },

  // ── Vertical and catalog discovery ──────────────────────────────────
  { key: "catalog.enabledVerticals", group: "Vertical and catalog discovery", label: "Enabled verticals",
    vertical: "global", evidence: "PARTIAL", requiresAuth: true, canonicalEndpoint: "/v1/customer/categories",
    canonicalDataModel: "catalog category", offlinePolicy: "NOT_APPLICABLE",
    blocker: "Inferred from category vertical field, no standalone enablement list (see appConfig.enabledVerticals).",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "catalog.serviceCategories", group: "Vertical and catalog discovery", label: "Service categories",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "/v1/customer/categories",
    canonicalDataModel: "catalog category", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "catalog.offerings", group: "Vertical and catalog discovery", label: "Offerings (service groups/master services)",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/categories/{category_slug}/offerings", canonicalDataModel: "catalog offering",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "catalog.jobTypes", group: "Vertical and catalog discovery", label: "Job types",
    vertical: "home_services", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/categories/{category_slug}/runtime", canonicalDataModel: "catalog runtime config",
    offlinePolicy: "NOT_APPLICABLE", blocker: "Job types resolved via category runtime payload; exact shape not traced this phase.",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "catalog.brands", group: "Vertical and catalog discovery", label: "Brands",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/catalog/brands", canonicalDataModel: "catalog brand",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "catalog.options", group: "Vertical and catalog discovery", label: "Options/add-ons",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/catalog/service-options", canonicalDataModel: "catalog service option",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "catalog.issueTypes", group: "Vertical and catalog discovery", label: "Questions and issue types",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/catalog/issue-types", canonicalDataModel: "catalog issue type",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "catalog.checklists", group: "Vertical and catalog discovery", label: "Checklists",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/service-jobs/{job_id}/checklists", canonicalDataModel: "ServiceJob checklist",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "catalog.serviceability", group: "Vertical and catalog discovery", label: "Serviceability",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/home-services/booking-drafts/{draft_id}/serviceability-check",
    canonicalDataModel: "serviceability result", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "live_openapi_introspection", exposableInUi: true },

  // ── Booking draft (canonical pipeline) ──────────────────────────────
  { key: "bookingDraft.create", group: "Booking draft", label: "Create draft",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/home-services/booking-drafts",
    canonicalDataModel: "BookingDraft (home_service_booking)", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookingDraft.update", group: "Booking draft", label: "Select service / job type / answer questions / etc.",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "PUT /v1/customer/home-services/booking-drafts/{draft_id}",
    canonicalDataModel: "BookingDraft", offlinePolicy: "LOCAL_DRAFT",
    blocker: "LOCAL_DRAFT only between edits -- every PUT still round-trips the server; see storage/draft/bookingDraftPersistence.ts.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookingDraft.attachPhotos", group: "Booking draft", label: "Attach customer photos",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/home-services/booking-drafts/{draft_id}/photos",
    canonicalDataModel: "BookingDraft", offlinePolicy: "MEDIA_UPLOAD",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookingDraft.serviceabilityCheck", group: "Booking draft", label: "Set zipcode/location",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/home-services/booking-drafts/{draft_id}/serviceability-check",
    canonicalDataModel: "BookingDraft", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookingDraft.priceEstimate", group: "Booking draft", label: "Retrieve estimate",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/home-services/booking-drafts/{draft_id}/price-estimate",
    canonicalDataModel: "BookingDraft.price_snapshot", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookingDraft.matchProviders", group: "Booking draft", label: "Match and price / select provider",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/home-services/booking-drafts/{draft_id}/match-providers",
    canonicalDataModel: "BookingDraft.provider_snapshot", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookingDraft.selectAddress", group: "Booking draft", label: "Select address",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "PUT /v1/customer/home-services/booking-drafts/{draft_id}",
    canonicalDataModel: "BookingDraft", offlinePolicy: "LOCAL_DRAFT",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookingDraft.validate", group: "Booking draft", label: "Validate draft / summary",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/home-services/booking-drafts/{draft_id}/summary",
    canonicalDataModel: "BookingDraft", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookingDraft.finalize", group: "Booking draft", label: "Finalize booking",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/home-services/booking-drafts/{draft_id}/confirm",
    canonicalDataModel: "ServiceBooking + ServiceJob", offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "Directly read: docstring/summary confirms 'Validates draft, creates ServiceBooking + ServiceJob'. NOTE: a second, parallel confirmation route exists for AI-chat-originated drafts -- POST /v1/customer/confirm/home-service-booking/{draft_id} (final_records/confirm_router.py, Sprint 19) -- both produce ServiceBooking+ServiceJob but via different draft models (structured booking-drafts vs AI-chat draft). Phase E must pick one canonical entry point per booking origin, not silently merge them.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookingDraft.finalizeIdempotent", group: "Booking draft", label: "Idempotent finalization",
    vertical: "home_services", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/home-services/booking-drafts/{draft_id}/confirm",
    canonicalDataModel: "ServiceBooking + ServiceJob", offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "final_records/confirm_router.py docstring explicitly claims idempotency ('duplicate submissions return the same result') for the AI-chat confirm path; the structured booking-drafts confirm path's idempotency guard was not independently re-verified this phase.",
    verificationSource: "router_source_read", exposableInUi: true },

  // ── Pricing ──
  { key: "pricing.priceRange", group: "Pricing", label: "Price range",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/home-services/booking-drafts/{draft_id}/price-estimate",
    canonicalDataModel: "BookingDraft.price_snapshot", offlinePolicy: "ONLINE_ONLY_MUTATION",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "pricing.standardPrice", group: "Pricing", label: "Standard price confirmation",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/home-services/booking-drafts/{draft_id}/confirm-price-choice",
    canonicalDataModel: "BookingDraft.price_snapshot.standard_price", offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "Only price_tier='standard' is supported; Low/Mid/High tier pricing is retired.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "pricing.visitFee", group: "Pricing", label: "Visit fee",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /customer/quotes/{quote_id}", canonicalDataModel: "Quote.visit_fee",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "router_source_read", exposableInUi: true },
  // ── Booking ──────────────────────────────────────────────────────────
  { key: "bookings.list", group: "Booking", label: "List customer bookings",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "GET /v1/customer/bookings",
    canonicalDataModel: "ServiceBooking", offlinePolicy: "NOT_APPLICABLE",
    blocker: "Directly read: home_service_assignment/customer_router.py list_bookings queries ServiceBooking filtered by customer_id.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookings.detail", group: "Booking", label: "Booking detail",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/bookings/{booking_id}", canonicalDataModel: "ServiceBooking",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookings.assignedProvider", group: "Booking", label: "Assigned provider",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/bookings/{booking_id}", canonicalDataModel: "ServiceBooking.provider_snapshot",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "Directly read _customer_safe_provider() -- only provider_name/rating/public_badges are ever exposed; internal_score and matching_score_snapshot are explicitly stripped server-side.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookings.status", group: "Booking", label: "Booking status",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/bookings/{booking_id}", canonicalDataModel: "ServiceBooking.status",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookings.schedule", group: "Booking", label: "Schedule information",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/bookings/{booking_id}", canonicalDataModel: "ServiceBooking.preferred_date",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookings.history", group: "Booking", label: "Booking history",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "GET /v1/customer/bookings",
    canonicalDataModel: "ServiceBooking", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookings.reschedule", group: "Booking", label: "Reschedule",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/bookings/{booking_id}/reschedule",
    canonicalDataModel: "ServiceBooking (via HomeServiceJobAssignmentService)", offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "REAFFIRMED THIS PHASE, CONTRARY TO PRIOR ASSUMPTION: directly read customer_router.py reschedule_booking -- it calls HomeServiceJobAssignmentService.customer_reschedule_booking, which operates on the canonical ServiceBooking, NOT the disconnected legacy /v1/bookings engine. This is real and connected as of MODULE-L5-29.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "bookings.cancel", group: "Booking", label: "Cancel",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/bookings/{booking_id}/cancel",
    canonicalDataModel: "ServiceBooking (via HomeServiceJobAssignmentService)", offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "REAFFIRMED THIS PHASE, CONTRARY TO PRIOR ASSUMPTION: directly read customer_router.py cancel_booking -- same canonical ServiceBooking path as reschedule. The genuinely DISCONNECTED engine is the separate /v1/bookings/* 'Booking Engine' (app/engines/booking/router.py, BookingService) -- that legacy engine must never be called by this app.",
    verificationSource: "router_source_read", exposableInUi: true },

  { key: "bookings.legacyBookingEngineWarning", group: "Booking", label: "Legacy /v1/bookings engine (do not use)",
    vertical: "home_services", evidence: "DISCONNECTED", requiresAuth: true,
    canonicalEndpoint: "/v1/bookings/*", canonicalDataModel: "BookingService (app/engines/booking) -- NOT ServiceBooking",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "Confirmed via direct read of app/engines/booking/router.py: a separate 'Booking Engine' (BookingService) mounted at /v1/bookings, entirely independent of the canonical final_records.ServiceBooking/ServiceJob pipeline the rest of this registry documents. This app must NEVER call any /v1/bookings/* route -- it exists only as a registry entry so a future contributor searching for 'booking cancel' doesn't wire up the wrong engine by accident.",
    verificationSource: "router_source_read", exposableInUi: false },

  // ── Service job and tracking ─────────────────────────────────────────
  { key: "serviceJob.detail", group: "Service job and tracking", label: "ServiceJob detail",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/jobs/{job_id}", canonicalDataModel: "ServiceJob",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "model_source_read", exposableInUi: true },
  { key: "serviceJob.assignedTechnician", group: "Service job and tracking", label: "Assigned technician",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/jobs/{job_id}", canonicalDataModel: "ServiceJob.assigned_staff_id",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "model_source_read", exposableInUi: true },
  { key: "serviceJob.timeline", group: "Service job and tracking", label: "Timeline",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/jobs/{job_id}/progress", canonicalDataModel: "ServiceJob progress events",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "serviceJob.currentStage", group: "Service job and tracking", label: "Current stage",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-jobs/{job_id}/tracking", canonicalDataModel: "ServiceJob.status",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "Status vocabulary confirmed against app/engines/execution/constants.py JS_* -- see domain/status.ts JOB_STATUSES.",
    verificationSource: "model_source_read", exposableInUi: true },
  { key: "serviceJob.onTheWay", group: "Service job and tracking", label: "On-the-way status",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-jobs/{job_id}/tracking", canonicalDataModel: "ServiceJob.status = on_the_way",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "model_source_read", exposableInUi: true },
  { key: "serviceJob.arrival", group: "Service job and tracking", label: "Arrival",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-jobs/{job_id}/tracking", canonicalDataModel: "ServiceJob.status = reached_site",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "model_source_read", exposableInUi: true },
  { key: "serviceJob.inspection", group: "Service job and tracking", label: "Inspection",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-jobs/{job_id}/tracking",
    canonicalDataModel: "ServiceJob.status = inspection_started/inspection_done", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "model_source_read", exposableInUi: true },
  { key: "serviceJob.estimatePending", group: "Service job and tracking", label: "Estimate pending",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-jobs/{job_id}/tracking",
    canonicalDataModel: "ServiceJob.status = quote_required", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "model_source_read", exposableInUi: true },
  { key: "serviceJob.workInProgress", group: "Service job and tracking", label: "Work in progress",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-jobs/{job_id}/tracking",
    canonicalDataModel: "ServiceJob.status = service_started", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "model_source_read", exposableInUi: true },
  { key: "serviceJob.workDone", group: "Service job and tracking", label: "Work done",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-jobs/{job_id}/tracking",
    canonicalDataModel: "ServiceJob.status = work_done", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "model_source_read", exposableInUi: true },
  { key: "serviceJob.completion", group: "Service job and tracking", label: "Completion",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-jobs/{job_id}/tracking",
    canonicalDataModel: "ServiceJob.status = completed, ServiceJob.completion_data", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "model_source_read", exposableInUi: true },
  { key: "serviceJob.liveLocationTracking", group: "Service job and tracking", label: "Location/tracking information",
    vertical: "home_services", evidence: "MISSING", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-jobs/{job_id}/tracking", canonicalDataModel: "ServiceJob",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "The tracking endpoint reflects discrete STATUS stages only (on_the_way, reached_site, ...), not live GPS coordinates -- ServiceJob has no lat/lng column. Do not fabricate a moving map/ETA; that data does not exist server-side.",
    verificationSource: "model_source_read", exposableInUi: false },

  // ── Inspection and quote ─────────────────────────────────────────────
  { key: "quote.inspectionStatus", group: "Inspection and quote", label: "Inspection status",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-jobs/{job_id}/tracking",
    canonicalDataModel: "ServiceJob.status", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "model_source_read", exposableInUi: true },
  { key: "quote.received", group: "Inspection and quote", label: "Quote received",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /customer/quotes/jobs/{job_id}", canonicalDataModel: "ServiceJobQuote",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "Directly read app/engines/quote_checklist/customer_router.py -- require_customer-guarded, ownership-checked via customer_id.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "quote.details", group: "Inspection and quote", label: "Quote details",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /customer/quotes/{quote_id}", canonicalDataModel: "ServiceJobQuote",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "router_source_read", exposableInUi: true },
  { key: "quote.expiry", group: "Inspection and quote", label: "Quote expiry",
    vertical: "home_services", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "GET /customer/quotes/{quote_id}", canonicalDataModel: "ServiceJobQuote",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "Route confirmed; exact expiry field name on ServiceJobQuoteService was not traced this phase (service.py not opened) -- see api/contracts/quotes.ts expires_at as a conservative optional field.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "quote.approval", group: "Inspection and quote", label: "Quote approval",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /customer/quotes/{quote_id}/approve", canonicalDataModel: "ServiceJobQuote",
    offlinePolicy: "IDEMPOTENT_MUTATION",
    blocker: "GENUINELY SUPPORTED, contrary to the phase-D default assumption of PARTIAL/MISSING: directly read the route, which requires an `Idempotency-Key` header -- the strongest idempotency evidence found anywhere in the customer API this phase.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "quote.rejection", group: "Inspection and quote", label: "Quote rejection",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /customer/quotes/{quote_id}/reject", canonicalDataModel: "ServiceJobQuote",
    offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "No Idempotency-Key parameter on this route (unlike approve) -- must not be retried automatically.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "quote.revised", group: "Inspection and quote", label: "Revised quote / request revision",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /customer/quotes/{quote_id}/request-revision", canonicalDataModel: "ServiceJobQuote",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "router_source_read", exposableInUi: true },
  { key: "quote.visitFeeHandling", group: "Inspection and quote", label: "Visit-fee handling",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /customer/quotes/{quote_id}", canonicalDataModel: "ServiceJobQuote.visit_fee",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "router_source_read", exposableInUi: true },
  { key: "quote.workBlockedUntilApproval", group: "Inspection and quote", label: "Work blocked until approval",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/jobs/{job_id}", canonicalDataModel: "ServiceJob.status = quote_required",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "Confirmed via app/engines/execution/constants.py ERR_ESTIMATE_APPROVAL_REQUIRED / MSG_ESTIMATE_APPROVAL_REQUIRED -- work cannot start server-side until the customer approves.",
    verificationSource: "model_source_read", exposableInUi: true },

  // ── Parts and change orders ──────────────────────────────────────────
  { key: "parts.customerVisible", group: "Parts and change orders", label: "Customer-visible parts",
    vertical: "home_services", evidence: "MISSING", requiresAuth: true, canonicalEndpoint: null,
    canonicalDataModel: "PartsRequest (execution engine)", offlinePolicy: "NOT_APPLICABLE",
    blocker: "The backend fully models a customer-facing lifecycle (PARTS_STATUS_CUSTOMER_APPROVAL_PENDING / _APPROVED / _REJECTED in app/engines/execution/constants.py) but NO customer-scoped route exposes it -- only /v1/provider/service-jobs/{id}/parts-requests* and /v1/staff/service-jobs/{id}/parts-requests* exist. This is a genuine backend gap: the domain concept exists, the API surface for it does not.",
    verificationSource: "model_source_read", exposableInUi: false },
  { key: "parts.addedCost", group: "Parts and change orders", label: "Added cost",
    vertical: "home_services", evidence: "MISSING", requiresAuth: true, canonicalEndpoint: null,
    canonicalDataModel: "PartsRequest", offlinePolicy: "NOT_APPLICABLE",
    blocker: "Same root cause as parts.customerVisible.", verificationSource: "model_source_read", exposableInUi: false },
  { key: "parts.approval", group: "Parts and change orders", label: "Customer approval requirement",
    vertical: "home_services", evidence: "ROLE_BLOCKED", requiresAuth: true,
    canonicalEndpoint: "/v1/provider/service-jobs/{job_id}/parts-requests/{parts_request_id}/approve",
    canonicalDataModel: "PartsRequest", offlinePolicy: "NOT_APPLICABLE",
    blocker: "The only approve/reject/install routes that exist are provider-scoped -- a customer identity cannot call them even though the status vocabulary implies a customer decision point.",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "parts.rejection", group: "Parts and change orders", label: "Rejection",
    vertical: "home_services", evidence: "ROLE_BLOCKED", requiresAuth: true,
    canonicalEndpoint: "/v1/provider/service-jobs/{job_id}/parts-requests/{parts_request_id}/reject",
    canonicalDataModel: "PartsRequest", offlinePolicy: "NOT_APPLICABLE",
    blocker: "Same root cause as parts.approval -- this route is provider-scoped only, no customer-callable equivalent exists.",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "parts.installationStatus", group: "Parts and change orders", label: "Installation status",
    vertical: "home_services", evidence: "ROLE_BLOCKED", requiresAuth: true,
    canonicalEndpoint: "/v1/provider/service-jobs/{job_id}/parts-requests/{parts_request_id}/install",
    canonicalDataModel: "PartsRequest", offlinePolicy: "NOT_APPLICABLE",
    blocker: "Same root cause as parts.approval -- install status is only ever written by the provider route; no customer-readable status projection exists either.",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "parts.priceTotalUpdate", group: "Parts and change orders", label: "Price-total update",
    vertical: "home_services", evidence: "MISSING", requiresAuth: true, canonicalEndpoint: null,
    canonicalDataModel: null, offlinePolicy: "NOT_APPLICABLE",
    blocker: "No customer-visible aggregate total that includes parts cost was found this phase.",
    verificationSource: "not_verified", exposableInUi: false },

  // ── Completion and payment information ──────────────────────────────
  { key: "completion.workCompletion", group: "Completion and payment information", label: "Work completion",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/jobs/{job_id}", canonicalDataModel: "ServiceJob.status = completed",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "model_source_read", exposableInUi: true },
  { key: "completion.customerAcknowledgement", group: "Completion and payment information", label: "Customer acknowledgement",
    vertical: "home_services", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "/v1/customer/direct-payments/{payment_id}/confirm", canonicalDataModel: "DirectPayment",
    offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "Confirming the direct payment is the closest verified acknowledgement action; a distinct 'I confirm the work is done' action separate from payment confirmation was not found this phase.",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "completion.directPayment", group: "Completion and payment information", label: "Direct payment to provider",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/direct-payments", canonicalDataModel: "DirectPayment",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "Confirmed via app/engines/execution/constants.py PAYMENT_MODE_HOME_SERVICES = 'customer_pays_provider_directly' -- there is no platform checkout; this app must never build one (Phase D section 8/25).",
    verificationSource: "model_source_read", exposableInUi: true },
  { key: "completion.amountDue", group: "Completion and payment information", label: "Amount due",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/direct-payments", canonicalDataModel: "DirectPayment",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "completion.visitFeeAdjustment", group: "Completion and payment information", label: "Visit-fee adjustment",
    vertical: "home_services", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "GET /customer/quotes/{quote_id}", canonicalDataModel: "ServiceJobQuote.visit_fee",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "Visit fee itself is visible on the quote; the specific 'visit fee is credited against the final job cost when work continues' adjustment rule was not independently traced in service code this phase.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "completion.usageCreditHidden", group: "Completion and payment information", label: "Usage-credit details hidden from customers",
    vertical: "global", evidence: "NOT_APPLICABLE", requiresAuth: true, canonicalEndpoint: null,
    canonicalDataModel: "TenantPackageAssignment / usage credits", offlinePolicy: "NOT_APPLICABLE",
    blocker: "By design (Phase A-C/D section 8/25): /v1/admin/usage-credits and related tenant-credit endpoints exist but are intentionally NOT surfaced to the customer app. This registry entry exists only to make that exclusion explicit and testable (see security search for 'usage_credit' imports).",
    verificationSource: "live_openapi_introspection", exposableInUi: false },
  { key: "completion.invoiceReceipt", group: "Completion and payment information", label: "Invoice or receipt availability",
    vertical: "home_services", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/service-invoices", canonicalDataModel: "ServiceInvoice",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "TWO parallel invoice surfaces are mounted: /v1/customer/invoices/* and /v1/customer/service-invoices/* (the latter also has apply-credit/confirm-payment/receipt sub-routes). Router source for either was not read this phase to determine which is canonical -- Phase E must resolve this, not silently pick one.",
    verificationSource: "live_openapi_introspection", exposableInUi: true },

  // ── Reviews ──────────────────────────────────────────────────────────
  { key: "reviews.eligibility", group: "Reviews", label: "Review eligibility",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/reviews/eligibility", canonicalDataModel: "CustomerReview eligibility",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "Handler function `check_eligibility` located directly in app/engines/customer_reviews/customer_router.py.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "reviews.create", group: "Reviews", label: "Create review",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/reviews", canonicalDataModel: "CustomerReview",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "reviews.preventDuplicate", group: "Reviews", label: "Prevent duplicate review",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/reviews/eligibility", canonicalDataModel: "CustomerReview eligibility",
    offlinePolicy: "NOT_APPLICABLE",
    blocker: "Enforced via the eligibility check (`already_reviewed` reason) -- see domain/status.ts REVIEW_ELIGIBILITY_REASONS.",
    verificationSource: "router_source_read", exposableInUi: true },
  { key: "reviews.ratingDimensions", group: "Reviews", label: "Rating dimensions",
    vertical: "home_services", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/reviews", canonicalDataModel: "CustomerReview",
    offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "Only a single overall `rating` field was confirmed this phase; whether the backend supports multi-dimension ratings was not traced (service layer not opened).",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "reviews.detail", group: "Reviews", label: "Review detail",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/reviews/{review_id}", canonicalDataModel: "CustomerReview",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },

  // ── Communication ────────────────────────────────────────────────────
  { key: "conversations.list", group: "Communication", label: "Conversations",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/chat/threads", canonicalDataModel: "ChatThread",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "conversations.messages", group: "Communication", label: "Messages",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/chat/threads/{thread_id}/messages", canonicalDataModel: "ChatMessage",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "conversations.attachments", group: "Communication", label: "Attachments",
    vertical: "home_services", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/chat/threads/{thread_id}/messages", canonicalDataModel: "ChatMessage attachment",
    offlinePolicy: "MEDIA_UPLOAD",
    blocker: "Media routes exist generically (/v1/media/*) but attachment wiring specific to chat messages was not traced this phase.",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "conversations.mediaAuthorization", group: "Communication", label: "Media authorization",
    vertical: "global", evidence: "PARTIAL", requiresAuth: true, canonicalEndpoint: "/v1/media/signed",
    canonicalDataModel: "signed media URL", offlinePolicy: "NOT_APPLICABLE",
    blocker: "A signed-media route is mounted (media_signed_router); its exact authorization model for customer-owned attachments was not traced this phase.",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "conversations.readReceipts", group: "Communication", label: "Read receipts",
    vertical: "home_services", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/chat/threads/{thread_id}/read", canonicalDataModel: "ChatThread read state",
    offlinePolicy: "IDEMPOTENT_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "conversations.support", group: "Communication", label: "Support conversation",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/complaints/{complaint_id}/messages", canonicalDataModel: "Complaint thread",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "conversations.complaintCreation", group: "Communication", label: "Complaint creation",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/complaints", canonicalDataModel: "Complaint",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "conversations.aiAssistant", group: "Communication", label: "DeepSeek AI assistant session",
    vertical: "global", evidence: "PARTIAL", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/ai/sessions", canonicalDataModel: "AI chat session",
    offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "TWO parallel AI session surfaces are mounted: /v1/customer/ai-chat/sessions* and /v1/customer/ai/sessions* (the latter additionally has draft-status/handoff/reset actions the former lacks). Router source for either was not read this phase -- Phase E/backend must confirm which is the current canonical DeepSeek entry point before any UI is built against it. Per architecture rule, the backend (not this app) owns all DeepSeek communication either way.",
    verificationSource: "live_openapi_introspection", exposableInUi: false },

  // ── Notifications ────────────────────────────────────────────────────
  { key: "notifications.list", group: "Notifications", label: "Notification list",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "GET /v1/customer/notifications",
    canonicalDataModel: "CustomerNotification", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "notifications.unreadCount", group: "Notifications", label: "Unread count",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/notifications/unread-count", canonicalDataModel: "CustomerNotification",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "notifications.markRead", group: "Notifications", label: "Mark read",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/customer/notifications/{notification_id}/read", canonicalDataModel: "CustomerNotification",
    offlinePolicy: "IDEMPOTENT_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "notifications.deepLinkTarget", group: "Notifications", label: "Deep-link target",
    vertical: "global", evidence: "PARTIAL", requiresAuth: true, canonicalEndpoint: "GET /v1/customer/notifications",
    canonicalDataModel: "CustomerNotification.deep_link", offlinePolicy: "NOT_APPLICABLE",
    blocker: "Field presence assumed conservatively (see api/contracts/notifications.ts); exact deep-link URL scheme was not confirmed against a real payload this phase -- Phase E must not build a router that assumes a specific scheme without re-verifying.",
    verificationSource: "not_verified", exposableInUi: false },
  { key: "notifications.pushRegistration", group: "Notifications", label: "Push registration",
    vertical: "global", evidence: "PARTIAL", requiresAuth: true, canonicalEndpoint: "/v1/mobile/push",
    canonicalDataModel: "push token registration", offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "mobile_push_router is mounted for the mobile surface generally; whether it is customer-scoped or staff-only was not confirmed this phase.",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "notifications.preferences", group: "Notifications", label: "Notification preferences",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/customer/notifications/preferences", canonicalDataModel: "NotificationPreferences",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },

  // ── Privacy and consent ──────────────────────────────────────────────
  { key: "privacy.consentRecords", group: "Privacy and consent", label: "Consent records",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true, canonicalEndpoint: "GET /v1/me/privacy/consents",
    canonicalDataModel: "consent record", offlinePolicy: "NOT_APPLICABLE",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "privacy.requestStatus", group: "Privacy and consent", label: "Privacy request status",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "GET /v1/me/privacy/requests/{request_id}", canonicalDataModel: "PrivacyRequest",
    offlinePolicy: "NOT_APPLICABLE", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "privacy.exportRequest", group: "Privacy and consent", label: "Export request",
    vertical: "global", evidence: "SOURCE_VERIFIED", requiresAuth: true,
    canonicalEndpoint: "POST /v1/me/privacy/requests/{request_id}/generate-export", canonicalDataModel: "PrivacyRequest export",
    offlinePolicy: "ONLINE_ONLY_MUTATION", verificationSource: "live_openapi_introspection", exposableInUi: true },
  { key: "privacy.deleteAccountRequest", group: "Privacy and consent", label: "Delete-account request",
    vertical: "global", evidence: "PARTIAL", requiresAuth: true, canonicalEndpoint: "POST /v1/me/privacy/requests",
    canonicalDataModel: "PrivacyRequest", offlinePolicy: "ONLINE_ONLY_MUTATION",
    blocker: "A generic privacy-request creation route exists; whether 'account deletion' is one of its accepted request types was not confirmed this phase (request-type enum not read).",
    verificationSource: "live_openapi_introspection", exposableInUi: true },
];

export function getCapability(key: string): CustomerCapability | undefined {
  return CUSTOMER_CAPABILITY_REGISTRY.find(c => c.key === key);
}

export function capabilitiesForVertical(vertical: string): CustomerCapability[] {
  return CUSTOMER_CAPABILITY_REGISTRY.filter(c => c.vertical === vertical || c.vertical === "global");
}

export function capabilitiesByEvidence(evidence: CustomerCapability["evidence"]): CustomerCapability[] {
  return CUSTOMER_CAPABILITY_REGISTRY.filter(c => c.evidence === evidence);
}
