import { ROUTE_NAMES, type RouteName } from "./route-names";

export type RouteId = keyof typeof ROUTE_NAMES;

export type NavigatorId = "system" | "authentication" | "main" | "booking" | "modal";

export type RouteAccessPolicy =
  | "public-system"
  | "public-authentication"
  | "authenticated"
  | "profile-required"
  | "marketplace-required"
  | "module-enabled"
  | "booking-owner-required"
  | "development-only";

export interface RouteDefinition {
  id: RouteId;
  name: RouteName;
  navigator: NavigatorId;
  access: RouteAccessPolicy;
  deepLinkEnabled: boolean;
  notificationEnabled: boolean;
  productionEnabled: boolean;
  analyticsName: string;
  /** Where to send the user if this route's guard rejects access. */
  fallbackRouteId: RouteId;
  /** Remote-config module key this route depends on, if any. */
  featureKey?: string;
}

/**
 * The single compiled source of truth for every route. Remote config may
 * reference a route by `id` (e.g. in `navigation.allowedRouteIds` or a
 * module's `routeId`) but can never invent a route that isn't listed here —
 * see remote-config-schema.ts's `routeIdPattern` plus the resolver logic in
 * route-guards.ts, which looks up `ROUTE_REGISTRY[id]` and treats an unknown
 * id as invalid rather than constructing a route from remote data.
 */
export const ROUTE_REGISTRY: Record<RouteId, RouteDefinition> = {
  startup: {
    id: "startup",
    name: ROUTE_NAMES.startup,
    navigator: "system",
    access: "public-system",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "startup",
    fallbackRouteId: "startup",
  },
  startupError: {
    id: "startupError",
    name: ROUTE_NAMES.startupError,
    navigator: "system",
    access: "public-system",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "startup_error",
    fallbackRouteId: "startup",
  },
  offlineStartup: {
    id: "offlineStartup",
    name: ROUTE_NAMES.offlineStartup,
    navigator: "system",
    access: "public-system",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "offline_startup",
    fallbackRouteId: "startup",
  },
  maintenance: {
    id: "maintenance",
    name: ROUTE_NAMES.maintenance,
    navigator: "system",
    access: "public-system",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "maintenance",
    fallbackRouteId: "startup",
  },
  mandatoryUpdate: {
    id: "mandatoryUpdate",
    name: ROUTE_NAMES.mandatoryUpdate,
    navigator: "system",
    access: "public-system",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "mandatory_update",
    fallbackRouteId: "startup",
  },
  unsupportedBuild: {
    id: "unsupportedBuild",
    name: ROUTE_NAMES.unsupportedBuild,
    navigator: "system",
    access: "public-system",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "unsupported_build",
    fallbackRouteId: "startup",
  },
  appUnavailable: {
    id: "appUnavailable",
    name: ROUTE_NAMES.appUnavailable,
    navigator: "system",
    access: "public-system",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "app_unavailable",
    fallbackRouteId: "startup",
  },
  baselineLanding: {
    id: "baselineLanding",
    name: ROUTE_NAMES.baselineLanding,
    navigator: "main",
    access: "public-system",
    deepLinkEnabled: true,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "baseline_landing",
    fallbackRouteId: "baselineLanding",
  },

  authentication: {
    id: "authentication",
    name: ROUTE_NAMES.authentication,
    navigator: "authentication",
    access: "public-authentication",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "authentication",
    fallbackRouteId: "baselineLanding",
  },

  home: {
    id: "home",
    name: ROUTE_NAMES.home,
    navigator: "main",
    access: "authenticated",
    deepLinkEnabled: true,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "home",
    fallbackRouteId: "baselineLanding",
  },
  categoryDetail: {
    id: "categoryDetail",
    name: ROUTE_NAMES.categoryDetail,
    navigator: "main",
    access: "authenticated",
    deepLinkEnabled: true,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "category_detail",
    fallbackRouteId: "home",
  },
  search: {
    id: "search",
    name: ROUTE_NAMES.search,
    navigator: "main",
    access: "authenticated",
    deepLinkEnabled: true,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "search",
    fallbackRouteId: "home",
  },
  serviceDetails: {
    id: "serviceDetails",
    name: ROUTE_NAMES.serviceDetails,
    navigator: "main",
    access: "authenticated",
    deepLinkEnabled: true,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "service_details",
    fallbackRouteId: "home",
  },
  bookingAssistant: {
    id: "bookingAssistant",
    name: ROUTE_NAMES.bookingAssistant,
    navigator: "booking",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "booking_assistant",
    fallbackRouteId: "home",
  },
  bookingDraft: {
    id: "bookingDraft",
    name: ROUTE_NAMES.bookingDraft,
    navigator: "booking",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "booking_draft",
    fallbackRouteId: "home",
  },
  bookingMedia: {
    id: "bookingMedia",
    name: ROUTE_NAMES.bookingMedia,
    navigator: "booking",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "booking_media",
    fallbackRouteId: "home",
  },
  addressSelection: {
    id: "addressSelection",
    name: ROUTE_NAMES.addressSelection,
    navigator: "booking",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "address_selection",
    fallbackRouteId: "home",
  },
  addressForm: {
    id: "addressForm",
    name: ROUTE_NAMES.addressForm,
    navigator: "booking",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "address_form",
    fallbackRouteId: "home",
  },
  serviceabilityCheck: {
    id: "serviceabilityCheck",
    name: ROUTE_NAMES.serviceabilityCheck,
    navigator: "booking",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "serviceability_check",
    fallbackRouteId: "home",
  },
  providerPreview: {
    id: "providerPreview",
    name: ROUTE_NAMES.providerPreview,
    navigator: "booking",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "provider_preview",
    fallbackRouteId: "home",
  },
  pricing: {
    id: "pricing",
    name: ROUTE_NAMES.pricing,
    navigator: "booking",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "pricing",
    fallbackRouteId: "home",
  },
  bargain: {
    id: "bargain",
    name: ROUTE_NAMES.bargain,
    navigator: "booking",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "bargain",
    fallbackRouteId: "home",
  },
  bookingReview: {
    id: "bookingReview",
    name: ROUTE_NAMES.bookingReview,
    navigator: "booking",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "booking_review",
    fallbackRouteId: "home",
  },
  bookingSuccess: {
    id: "bookingSuccess",
    name: ROUTE_NAMES.bookingSuccess,
    navigator: "booking",
    access: "booking-owner-required",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "booking_success",
    fallbackRouteId: "baselineLanding",
  },
  bookingsList: {
    id: "bookingsList",
    name: ROUTE_NAMES.bookingsList,
    navigator: "main",
    access: "authenticated",
    deepLinkEnabled: true,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "bookings_list",
    fallbackRouteId: "home",
  },
  bookingDetail: {
    id: "bookingDetail",
    name: ROUTE_NAMES.bookingDetail,
    navigator: "main",
    access: "booking-owner-required",
    deepLinkEnabled: true,
    notificationEnabled: true,
    productionEnabled: true,
    analyticsName: "booking_detail",
    fallbackRouteId: "home",
  },
  tracking: {
    id: "tracking",
    name: ROUTE_NAMES.tracking,
    navigator: "main",
    access: "booking-owner-required",
    deepLinkEnabled: false,
    notificationEnabled: true,
    productionEnabled: true,
    analyticsName: "tracking",
    fallbackRouteId: "home",
  },
  quoteDecision: {
    id: "quoteDecision",
    name: ROUTE_NAMES.quoteDecision,
    navigator: "main",
    access: "booking-owner-required",
    deepLinkEnabled: false,
    notificationEnabled: true,
    productionEnabled: true,
    analyticsName: "quote_decision",
    fallbackRouteId: "home",
  },
  notifications: {
    id: "notifications",
    name: ROUTE_NAMES.notifications,
    navigator: "main",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: false,
    analyticsName: "notifications",
    fallbackRouteId: "baselineLanding",
  },
  rewards: {
    id: "rewards",
    name: ROUTE_NAMES.rewards,
    navigator: "main",
    access: "module-enabled",
    deepLinkEnabled: true,
    notificationEnabled: false,
    productionEnabled: false,
    analyticsName: "rewards",
    fallbackRouteId: "baselineLanding",
    featureKey: "rewards",
  },
  profile: {
    id: "profile",
    name: ROUTE_NAMES.profile,
    navigator: "main",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "profile",
    fallbackRouteId: "baselineLanding",
  },
  sessions: {
    id: "sessions",
    name: ROUTE_NAMES.sessions,
    navigator: "main",
    access: "authenticated",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: true,
    analyticsName: "sessions",
    fallbackRouteId: "profile",
  },
  support: {
    id: "support",
    name: ROUTE_NAMES.support,
    navigator: "main",
    access: "public-system",
    deepLinkEnabled: true,
    notificationEnabled: false,
    productionEnabled: false,
    analyticsName: "support",
    fallbackRouteId: "baselineLanding",
  },
  legalTerms: {
    id: "legalTerms",
    name: ROUTE_NAMES.legalTerms,
    navigator: "modal",
    access: "public-system",
    deepLinkEnabled: true,
    notificationEnabled: false,
    productionEnabled: false,
    analyticsName: "legal_terms",
    fallbackRouteId: "baselineLanding",
  },
  legalPrivacy: {
    id: "legalPrivacy",
    name: ROUTE_NAMES.legalPrivacy,
    navigator: "modal",
    access: "public-system",
    deepLinkEnabled: true,
    notificationEnabled: false,
    productionEnabled: false,
    analyticsName: "legal_privacy",
    fallbackRouteId: "baselineLanding",
  },

  designSystemShowcase: {
    id: "designSystemShowcase",
    name: ROUTE_NAMES.designSystemShowcase,
    navigator: "modal",
    access: "development-only",
    deepLinkEnabled: false,
    notificationEnabled: false,
    productionEnabled: false,
    analyticsName: "design_system_showcase",
    fallbackRouteId: "baselineLanding",
  },
};

export function getRouteDefinition(id: string): RouteDefinition | undefined {
  return (ROUTE_REGISTRY as Record<string, RouteDefinition>)[id];
}

export function isKnownRouteId(id: string): id is RouteId {
  return id in ROUTE_REGISTRY;
}
