/** Shared guidance, not completion state: visiting a page never completes it. */
export const CATALOG_SETUP_STEPS = [
  { key: "categories", label: "Categories", href: "/admin/categories", prerequisite: "Start here. Choose Home Services as the vertical.", task: "Create the top-level service category and keep it active.", done: "A category exists to contain your service groups.", example: "Home Services → Appliance Services", optional: false },
  { key: "groups", label: "Service Groups", href: "/admin/service-groups", prerequisite: "Create a category first.", task: "Create a group under the correct category. Groups organise related master services; they are not bookable jobs.", done: "Each group belongs to the intended category.", example: "Appliance Services → AC Services", optional: false },
  { key: "services", label: "Service Families", href: "/admin/master-services", prerequisite: "Create the parent service group first.", task: "Create one family such as Air Conditioner, not separate Installation/Repair families. These are the existing Master Service records, not another hierarchy level. Providers enter their own prices.", done: "Each family has the correct group and a job-type-neutral name.", example: "Cooling → Air Conditioner", optional: false },
  { key: "types-brands", label: "Types & Brands", href: "/admin/types-brands", prerequisite: "Create the master service first so values can be mapped to it.", task: "Create reusable types and brands, then map applicable values to the service. In Blueprint Setup → Dimensions, choose whether providers/customers must select them.", done: "Applicable types and brands are mapped. Skip if this service has no variants or brands.", example: "Types: Split AC, Window AC · Brands: the brands you support", optional: true },
  { key: "checklists", label: "Checklist Library", href: "/admin/checklists", prerequisite: "Decide which checks the technician must perform.", task: "Create a reusable template, add its items, and publish its version. Attach that published version to the exact service/job type in Blueprint Setup → Checklist.", done: "A published checklist version is available to map, if the service needs a checklist.", example: "AC Installation → Pre-work safety checks", optional: true },
  { key: "workspace", label: "Job-Type Blueprints", href: "/admin/catalog-workspace", prerequisite: "Create the service family and applicable library values first.", task: "Select the family, attach only the supported job types you offer, then configure each job type's workflow, dimensions and requirements. This is the configuration screen for the same catalog, not another service layer.", done: "Review all offered job types, then publish the validated blueprint. Custom journeys are optional.", example: "Air Conditioner → Installation → Workflow → Review", optional: false },
] as const;

export const BLUEPRINT_SETUP_STEPS = [
  { key: "overview", label: "Start", help: "Confirm the selected service and job type. Repeat this sequence for each job type you offer." },
  { key: "workflow", label: "Workflow", help: "Set pricing behavior and execution requirements first. Save journey edits explicitly; providers set monetary amounts." },
  { key: "dimensions", label: "Dimensions", help: "Enable mapped types, brands and other attributes only where needed. Set who selects them and whether they affect pricing." },
  { key: "problems", label: "Problems & Questions", help: "Configure relevant customer problems and conditional questions. Avoid asking Type or Brand twice if Dimensions already captures it." },
  { key: "checklist", label: "Checklist", help: "Map a published library version to this exact job type. Check its actor, required setting and completion gate against Workflow." },
  { key: "tenant_rules", label: "Provider Requirements", help: "Review provider setup requirements. These reuse Dimensions and Workflow settings, not a separate copy of them." },
  { key: "preview", label: "Review & Publishing", help: "Save journey and checklist edits, review the derived experience, then publish a validated full blueprint release. Individual settings still take effect when saved." },
] as const;
