"""Checklist Catalog Engine — controlled vocabularies.

All enums here are validated allowlists, not free text. Frontend flags must
never bypass these — the backend is the sole authority (see service.py /
gate.py enforcement).
"""

# ── Template ──────────────────────────────────────────────────────────────
PURPOSE_PRE_ARRIVAL = "PRE_ARRIVAL"
PURPOSE_INSPECTION = "INSPECTION"
PURPOSE_PRE_WORK = "PRE_WORK"
PURPOSE_EXECUTION = "EXECUTION"
PURPOSE_SAFETY = "SAFETY"
PURPOSE_COMPLETION = "COMPLETION"
PURPOSE_HANDOVER = "HANDOVER"
TEMPLATE_PURPOSES = {
    PURPOSE_PRE_ARRIVAL, PURPOSE_INSPECTION, PURPOSE_PRE_WORK, PURPOSE_EXECUTION,
    PURPOSE_SAFETY, PURPOSE_COMPLETION, PURPOSE_HANDOVER,
}

TEMPLATE_STATUS_ACTIVE = "active"
TEMPLATE_STATUS_ARCHIVED = "archived"
TEMPLATE_STATUSES = {TEMPLATE_STATUS_ACTIVE, TEMPLATE_STATUS_ARCHIVED}

OWNER_SCOPE_PLATFORM = "PLATFORM"
OWNER_SCOPE_TENANT = "TENANT"
OWNER_SCOPES = {OWNER_SCOPE_PLATFORM, OWNER_SCOPE_TENANT}

# ── Template version ─────────────────────────────────────────────────────
VERSION_DRAFT = "DRAFT"
VERSION_PUBLISHED = "PUBLISHED"
VERSION_ARCHIVED = "ARCHIVED"
VERSION_STATUSES = {VERSION_DRAFT, VERSION_PUBLISHED, VERSION_ARCHIVED}

# ── Item types ────────────────────────────────────────────────────────────
ITEM_TYPE_CHECKBOX = "CHECKBOX"
ITEM_TYPE_YES_NO = "YES_NO"
ITEM_TYPE_SHORT_TEXT = "SHORT_TEXT"
ITEM_TYPE_LONG_TEXT = "LONG_TEXT"
ITEM_TYPE_NUMBER = "NUMBER"
ITEM_TYPE_MEASUREMENT = "MEASUREMENT"
ITEM_TYPE_SINGLE_SELECT = "SINGLE_SELECT"
ITEM_TYPE_MULTI_SELECT = "MULTI_SELECT"
ITEM_TYPE_PHOTO = "PHOTO"
ITEM_TYPE_DOCUMENT = "DOCUMENT"
ITEM_TYPE_SIGNATURE = "SIGNATURE"
ITEM_TYPES = {
    ITEM_TYPE_CHECKBOX, ITEM_TYPE_YES_NO, ITEM_TYPE_SHORT_TEXT, ITEM_TYPE_LONG_TEXT,
    ITEM_TYPE_NUMBER, ITEM_TYPE_MEASUREMENT, ITEM_TYPE_SINGLE_SELECT,
    ITEM_TYPE_MULTI_SELECT, ITEM_TYPE_PHOTO, ITEM_TYPE_DOCUMENT, ITEM_TYPE_SIGNATURE,
}
EVIDENCE_CAPABLE_ITEM_TYPES = {ITEM_TYPE_PHOTO, ITEM_TYPE_DOCUMENT, ITEM_TYPE_SIGNATURE}

# ── Mapping ───────────────────────────────────────────────────────────────
ACTOR_TECHNICIAN = "TECHNICIAN"
ACTOR_STAFF = "STAFF"
ACTOR_TENANT_ADMIN = "TENANT_ADMIN"
ACTOR_CUSTOMER = "CUSTOMER"
ACTORS = {ACTOR_TECHNICIAN, ACTOR_STAFF, ACTOR_TENANT_ADMIN, ACTOR_CUSTOMER}

USAGE_DISABLED = "DISABLED"
USAGE_OPTIONAL = "OPTIONAL"
USAGE_REQUIRED = "REQUIRED"
USAGES = {USAGE_DISABLED, USAGE_OPTIONAL, USAGE_REQUIRED}

GATE_NONE = "NONE"
GATE_BEFORE_INSPECTION_COMPLETE = "REQUIRE_BEFORE_INSPECTION_COMPLETE"
GATE_BEFORE_ESTIMATE_SUBMISSION = "REQUIRE_BEFORE_ESTIMATE_SUBMISSION"
GATE_BEFORE_WORK_START = "REQUIRE_BEFORE_WORK_START"
GATE_BEFORE_JOB_COMPLETION = "REQUIRE_BEFORE_JOB_COMPLETION"
GATE_BEFORE_HANDOVER = "REQUIRE_BEFORE_HANDOVER"
COMPLETION_GATES = {
    GATE_NONE, GATE_BEFORE_INSPECTION_COMPLETE, GATE_BEFORE_ESTIMATE_SUBMISSION,
    GATE_BEFORE_WORK_START, GATE_BEFORE_JOB_COMPLETION, GATE_BEFORE_HANDOVER,
}

# Purpose -> gates it may legally be configured with. Prevents e.g. a
# COMPLETION-purpose checklist being wired as a pre-inspection gate.
PURPOSE_ALLOWED_GATES = {
    PURPOSE_PRE_ARRIVAL: {GATE_NONE, GATE_BEFORE_WORK_START},
    PURPOSE_INSPECTION: {GATE_NONE, GATE_BEFORE_INSPECTION_COMPLETE, GATE_BEFORE_ESTIMATE_SUBMISSION},
    PURPOSE_PRE_WORK: {GATE_NONE, GATE_BEFORE_WORK_START},
    PURPOSE_EXECUTION: {GATE_NONE, GATE_BEFORE_JOB_COMPLETION},
    PURPOSE_SAFETY: {GATE_NONE, GATE_BEFORE_WORK_START, GATE_BEFORE_JOB_COMPLETION},
    PURPOSE_COMPLETION: {GATE_NONE, GATE_BEFORE_JOB_COMPLETION, GATE_BEFORE_HANDOVER},
    PURPOSE_HANDOVER: {GATE_NONE, GATE_BEFORE_HANDOVER},
}

MAPPING_STATUS_ACTIVE = "active"
MAPPING_STATUS_DISABLED = "disabled"
MAPPING_STATUSES = {MAPPING_STATUS_ACTIVE, MAPPING_STATUS_DISABLED}

# ── Job checklist instance ───────────────────────────────────────────────
INSTANCE_NOT_STARTED = "NOT_STARTED"
INSTANCE_IN_PROGRESS = "IN_PROGRESS"
INSTANCE_COMPLETED = "COMPLETED"
INSTANCE_BLOCKED = "BLOCKED"
INSTANCE_WAIVED = "WAIVED"
INSTANCE_STATES = {
    INSTANCE_NOT_STARTED, INSTANCE_IN_PROGRESS, INSTANCE_COMPLETED,
    INSTANCE_BLOCKED, INSTANCE_WAIVED,
}

# ── Error codes (stable, machine-readable) ───────────────────────────────
ERR_REQUIRED_CHECKLIST_INCOMPLETE = "REQUIRED_CHECKLIST_INCOMPLETE"
ERR_CHECKLIST_CONFIGURATION_UNRESOLVED = "CHECKLIST_CONFIGURATION_UNRESOLVED"
ERR_CHECKLIST_VERSION_NOT_PUBLISHED = "CHECKLIST_VERSION_NOT_PUBLISHED"
ERR_CHECKLIST_ITEM_VALIDATION_FAILED = "CHECKLIST_ITEM_VALIDATION_FAILED"
ERR_CHECKLIST_EVIDENCE_REQUIRED = "CHECKLIST_EVIDENCE_REQUIRED"
ERR_CHECKLIST_ACTOR_NOT_AUTHORIZED = "CHECKLIST_ACTOR_NOT_AUTHORIZED"
