import Link from "next/link";
import { BadgeCheck, FileCheck2, MapPin, ShieldCheck, Star, Wrench } from "lucide-react";
import { BookingChoices } from "../components/SiteChrome";
import { cities, services, siteUrl } from "../lib/site";

export default function HomePage() {
  const schema = { "@context": "https://schema.org", "@type": "Organization", name: "Fuvay", url: siteUrl, areaServed: { "@type": "State", name: "Punjab" }, description: "PIN-code based home-service booking platform for Punjab." };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}/>
    <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow"><MapPin size={15}/> Built for Punjab, PIN code by PIN code</span><h1>Home service that begins with <em>real availability.</em></h1><p className="lead">Tell us your PIN code, choose only from services a local provider has published, and keep one clear record from booking to warranty.</p><BookingChoices/><div className="trust-row"><span><BadgeCheck/> Provider status shown clearly</span><span><FileCheck2/> Downloadable warranty evidence</span></div></div><div className="hero-visual" aria-label="Popular home services"><div className="visual-note"><span>Service availability</span><strong>Checked for your PIN code</strong></div>{services.slice(0,4).map((service, index) => <div className={`service-orb orb-${index+1}`} key={service.slug}><img src={service.image} alt={service.name}/><span>{service.name}</span></div>)}</div></div></section>
    <section className="proof"><div className="shell proof-grid"><div><strong>One booking record</strong><span>Across customer, provider and technician apps</span></div><div><strong>Provider-owned prices</strong><span>Shown before fixed-price confirmation</span></div><div><strong>Warranty evidence</strong><span>Provider details retained for the warranty period</span></div></div></section>
    <section className="section shell"><div className="section-head"><div><span className="kicker">Popular services</span><h2>Book what providers near you actually offer.</h2></div><Link className="text-link" href="/services/">View all services →</Link></div><div className="service-grid">{services.map(service => <Link className="service-card" href={`/services/${service.slug}/`} key={service.slug}><div className="service-image"><img src={service.image} alt=""/></div><div><h3>{service.name}</h3><p className="punjabi">{service.punjabi}</p><p>{service.description}</p><span>Check availability →</span></div></Link>)}</div></section>
    <section className="section dark"><div className="shell process-grid"><div><span className="kicker amber">A better booking path</span><h2>Less guessing. More evidence.</h2><p>Fuvay connects what customers see with what providers configure and technicians complete on the ground.</p></div><ol><li><b>01</b><div><strong>Start with your PIN code</strong><span>If no selected provider service is bookable there, we say so.</span></div></li><li><b>02</b><div><strong>Confirm the service and address</strong><span>Fixed prices or inspection terms are shown before booking.</span></div></li><li><b>03</b><div><strong>Track the job</strong><span>Assignment, arrival, quote approval and completion stay connected.</span></div></li><li><b>04</b><div><strong>Keep your warranty record</strong><span>Download provider details and service evidence after completion.</span></div></li></ol></div></section>
    <section className="section shell"><div className="section-head"><div><span className="kicker">Punjab coverage</span><h2>Local landing pages for the cities we serve.</h2></div></div><div className="city-list">{cities.map(city => <Link href={`/cities/${city.slug}/`} key={city.slug}>{city.name}<span>→</span></Link>)}</div></section>
    <section className="section shell"><div className="provider-banner"><div><span className="kicker">For service businesses</span><h2>Run bookings, technicians, credits and service quality in one place.</h2><p>Sign up, complete business approval, publish only the services and PIN codes you can serve, then become bookable after approval.</p><a className="button light" href="/providers/">Explore provider tools</a></div><div className="provider-points"><span><Wrench/> Technician seats follow your plan</span><span><Star/> Quality signals build account health</span><span><ShieldCheck/> Business approval before bookability</span></div></div></section>
    <section className="section final-cta"><div className="shell"><span className="kicker">Ready when you are</span><h2>Check your PIN code and book in the channel you already use.</h2><BookingChoices compact/></div></section>
  </>;
}
