"use client";
import { TableSurface } from "@serviceos/design-system";

import Link from "next/link";
import { useCallback, useMemo, useState } from "react";
import {
  Activity, AlertTriangle, Boxes, CheckCircle2, ChevronRight, CircleOff,
  Clock3, Cpu, FileClock, Filter, GitBranch, KeyRound, Layers3, Lock,
  RefreshCw, Search, ServerCog, ShieldCheck, SlidersHorizontal, Users,
} from "lucide-react";
import { AdminLayout } from "../../../components/layout/AdminLayout";
import { Badge, Btn, Card, Modal, Pagination, SectionHeader, Skeleton, SummaryCard } from "../../../components/shared/ui";
import { useApi } from "../../../hooks/useApi";
import {
  engineMgmtApi, rolesPermissionsApi,
  type EngineControlPlane, type EngineVerticalUsage,
  type EnterpriseEngineAuditLog, type EnterpriseTenantOverride,
  type RuntimeEngineItem,
} from "../../../lib/api";

type Tab = "overview" | "runtime" | "verticals" | "dependencies" | "overrides" | "health" | "access" | "audit";
const LEGACY_TAB_REDIRECTS: Record<string, Tab> = {
  "category-matrix": "verticals", "package-entitlements": "overview",
  permissions: "access", "tenant-overrides": "overrides", "audit-logs": "audit", all: "runtime",
};
const TABS: { id: Tab; label: string; icon: React.ReactNode }[] = [
  { id: "overview", label: "Overview", icon: <ServerCog size={15} /> },
  { id: "runtime", label: "Runtime inventory", icon: <Cpu size={15} /> },
  { id: "verticals", label: "Vertical usage", icon: <Layers3 size={15} /> },
  { id: "dependencies", label: "Dependencies", icon: <GitBranch size={15} /> },
  { id: "overrides", label: "Tenant exceptions", icon: <SlidersHorizontal size={15} /> },
  { id: "health", label: "Health", icon: <Activity size={15} /> },
  { id: "access", label: "Access control", icon: <KeyRound size={15} /> },
  { id: "audit", label: "Audit trail", icon: <FileClock size={15} /> },
];
const input: React.CSSProperties = { height: 38, border: "1px solid var(--border)", borderRadius: "var(--radius-md)", background: "var(--surface)", color: "var(--text-primary)", padding: "0 11px", fontSize: 13, fontFamily: "inherit", outline: "none" };
const th: React.CSSProperties = { padding: "11px 14px", textAlign: "left", fontSize: 10, fontWeight: 700, color: "var(--text-tertiary)", letterSpacing: ".08em", textTransform: "uppercase", borderBottom: "1px solid var(--border)", background: "var(--surface-sunken)", whiteSpace: "nowrap" };
const td: React.CSSProperties = { padding: "12px 14px", fontSize: 13, color: "var(--text-primary)", borderBottom: "1px solid var(--border)", verticalAlign: "middle" };

function LoadingRows({ count = 5 }: { count?: number }) { return <div style={{ display: "grid", gap: 10 }}>{Array.from({ length: count }).map((_, i) => <Skeleton key={i} height={46} />)}</div>; }
function Metric({ label, value, note, tone = "neutral", icon }: { label: string; value: number | string; note: string; tone?: "neutral" | "success" | "warning" | "danger"; icon: React.ReactNode }) {
  return <SummaryCard label={label} value={value} sub={note} icon={icon} tone={tone === "neutral" ? undefined : tone} />;
}
function StateBadge({ state }: { state: RuntimeEngineItem["runtime_state"] }) {
  if (state === "operational") return <Badge variant="success">Operational</Badge>;
  if (state === "unconfigured") return <Badge variant="warning">Needs governance</Badge>;
  if (state === "configured_not_mounted") return <Badge variant="danger">Not mounted</Badge>;
  return <Badge variant="muted">Inactive</Badge>;
}
function Pager({ page, pages, total, onPage }: { page: number; pages: number; total: number; onPage: (page: number) => void }) {
  return <Pagination page={page} pageSize={25} total={total} pageCount={pages} onPage={onPage} />;
}

function Overview({ data, loading }: { data: EngineControlPlane | null; loading: boolean }) {
  if (loading && !data) return <LoadingRows />;
  if (!data) return <Card><p style={{ color: "var(--text-secondary)" }}>Runtime inventory is unavailable.</p></Card>;
  const s = data.summary;
  const attention = data.engines.filter(i => i.runtime_state === "configured_not_mounted" || i.runtime_state === "unconfigured");
  const active = data.engines.filter(i => i.active_vertical_count > 0);
  return <div style={{ display: "grid", gap: 16 }}>
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12 }}>
      <Metric label="Registered" value={s.registered} note="Canonical runtime definitions" icon={<Boxes size={18} />} />
      <Metric label="Mounted" value={s.mounted} note="Exposed by the running API" tone="success" icon={<CheckCircle2 size={18} />} />
      <Metric label="Operational" value={s.operational} note="Mounted and governed" tone="success" icon={<Activity size={18} />} />
      <Metric label="Configuration drift" value={s.configuration_drift} note="Needs review before rollout" tone={s.configuration_drift ? "warning" : "success"} icon={<AlertTriangle size={18} />} />
      <Metric label="Legacy aliases" value={s.legacy_aliases} note="Collapsed into canonical engines" tone={s.legacy_aliases ? "warning" : "neutral"} icon={<GitBranch size={18} />} />
      <Metric label="Enabled verticals" value={s.enabled_verticals} note="Allowed to serve tenants" icon={<Layers3 size={18} />} />
    </div>
    <div style={{ display: "grid", gridTemplateColumns: "minmax(0, 1.45fr) minmax(300px, .75fr)", gap: 16 }}>
      <Card><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 18 }}><div><h3 style={{ margin: 0, fontSize: 16 }}>Runtime attention queue</h3><p style={{ margin: "5px 0 0", fontSize: 12, color: "var(--text-secondary)" }}>Only deployment and governance mismatches appear here.</p></div><Badge variant={attention.length ? "warning" : "success"}>{attention.length} items</Badge></div>
        {attention.length ? attention.slice(0, 10).map(item => <div key={item.engine_key} style={{ display: "grid", gridTemplateColumns: "minmax(180px,1fr) auto auto", gap: 12, alignItems: "center", padding: "12px 0", borderTop: "1px solid var(--border)" }}><div><div style={{ fontSize: 13, fontWeight: 650 }}>{item.display_name}</div><code style={{ fontSize: 11, color: "var(--text-tertiary)" }}>{item.engine_key}</code></div><StateBadge state={item.runtime_state} />{item.database_key ? <Link href={`/admin/engines/${item.database_key}`}><Btn size="xs" variant="secondary">Review</Btn></Link> : <span />}</div>) : <div style={{ padding: 34, textAlign: "center", color: "var(--text-secondary)" }}><CheckCircle2 size={28} color="var(--success)" /><div style={{ fontWeight: 650, marginTop: 8 }}>Runtime and governance are aligned</div></div>}
      </Card>
      <Card><h3 style={{ margin: "0 0 6px", fontSize: 16 }}>Current project scope</h3><p style={{ margin: "0 0 16px", fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 }}>Only engines used by enabled verticals are customer-serving. Future verticals remain isolated.</p><div style={{ display: "grid", gap: 9 }}>{active.slice(0, 8).map(item => <div key={item.engine_key} style={{ display: "flex", alignItems: "center", gap: 9, padding: 9, border: "1px solid var(--border)", borderRadius: "var(--radius-md)" }}><ShieldCheck size={15} color="var(--success)" /><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 12, fontWeight: 650, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{item.display_name}</div><div style={{ fontSize: 10, color: "var(--text-tertiary)" }}>{item.active_vertical_count} active vertical{item.active_vertical_count === 1 ? "" : "s"}</div></div><StateBadge state={item.runtime_state} /></div>)}</div><div style={{ marginTop: 14, paddingTop: 12, borderTop: "1px solid var(--border)", fontSize: 10, color: "var(--text-tertiary)" }}>Generated {new Date(data.generated_at).toLocaleString()}</div></Card>
    </div>
    {(s.legacy_aliases > 0 || s.orphaned_records > 0) && <Card style={{ borderColor: "color-mix(in srgb, var(--warning) 35%, var(--border))" }}><div style={{ display: "flex", gap: 12 }}><AlertTriangle size={18} color="var(--warning)" /><div><div style={{ fontSize: 13, fontWeight: 700 }}>Legacy records are isolated from runtime decisions</div><div style={{ fontSize: 12, color: "var(--text-secondary)", marginTop: 4 }}>{s.legacy_aliases} aliases are resolved to canonical engines and {s.orphaned_records} orphaned records are excluded from operational totals.</div></div></div></Card>}
  </div>;
}

function Runtime({ data, loading }: { data: EngineControlPlane | null; loading: boolean }) {
  const [search, setSearch] = useState(""); const [state, setState] = useState(""); const [category, setCategory] = useState(""); const [page, setPage] = useState(1); const size = 20;
  const categories = useMemo(() => Array.from(new Set((data?.engines ?? []).map(i => i.category))).sort(), [data]);
  const filtered = useMemo(() => (data?.engines ?? []).filter(i => { const q = search.toLowerCase(); return (!q || `${i.display_name} ${i.engine_key} ${i.api_prefix}`.toLowerCase().includes(q)) && (!state || i.runtime_state === state) && (!category || i.category === category); }), [data, search, state, category]);
  const pages = Math.max(1, Math.ceil(filtered.length / size)); const rows = filtered.slice((page - 1) * size, page * size);
  return <Card><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16 }}><div><h3 style={{ margin: 0, fontSize: 16 }}>Canonical runtime inventory</h3><p style={{ margin: "5px 0 0", fontSize: 12, color: "var(--text-secondary)" }}>Deployment, governance, and active usage in one view.</p></div><Badge variant="muted">{filtered.length} engines</Badge></div><div style={{ display: "grid", gridTemplateColumns: "minmax(240px,1fr) 190px 170px", gap: 8, marginBottom: 16 }}><label style={{ position: "relative" }}><Search size={14} style={{ position: "absolute", left: 11, top: 12, color: "var(--text-tertiary)" }} /><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search name, key, or API prefix" style={{ ...input, width: "100%", paddingLeft: 32 }} /></label><select value={state} onChange={e => { setState(e.target.value); setPage(1); }} style={input}><option value="">All runtime states</option><option value="operational">Operational</option><option value="unconfigured">Needs governance</option><option value="configured_not_mounted">Not mounted</option><option value="inactive">Inactive</option></select><select value={category} onChange={e => { setCategory(e.target.value); setPage(1); }} style={input}><option value="">All domains</option>{categories.map(v => <option key={v}>{v}</option>)}</select></div>
    {loading && !data ? <LoadingRows /> : <div style={{ overflowX: "auto", border: "1px solid var(--border)", borderRadius: "var(--radius-lg)" }}><TableSurface style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr>{["Engine", "Domain", "Runtime", "Governance", "Active use", "API surface", ""].map(h => <th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{rows.map(i => <tr key={i.engine_key}><td style={td}><div style={{ fontWeight: 650 }}>{i.display_name}</div><code style={{ fontSize: 11, color: "var(--text-tertiary)" }}>{i.engine_key} · v{i.version}</code>{i.legacy_aliases.length > 0 && <div style={{ marginTop: 5 }}><Badge variant="warning">{i.legacy_aliases.length} legacy aliases</Badge></div>}</td><td style={td}><Badge variant="muted">{i.category}</Badge></td><td style={td}><StateBadge state={i.runtime_state} /></td><td style={td}>{i.configured ? <CheckCircle2 size={14} color="var(--success)" /> : <CircleOff size={14} color="var(--text-tertiary)" />} <span style={{ marginLeft: 6, color: "var(--text-secondary)" }}>{i.global_status.replaceAll("_", " ")}</span></td><td style={td}><b>{i.active_vertical_count}</b> <span style={{ color: "var(--text-tertiary)" }}>verticals</span></td><td style={td}><code style={{ fontSize: 11 }}>{i.api_prefix}</code><div style={{ fontSize: 10, color: "var(--text-tertiary)", marginTop: 4 }}>{i.endpoint_count} declared endpoints</div></td><td style={td}>{i.database_key ? <Link href={`/admin/engines/${i.database_key}`}><Btn size="xs" variant="secondary">Inspect</Btn></Link> : <Badge variant="muted">Registry only</Badge>}</td></tr>)}{!rows.length && <tr><td colSpan={7} style={{ padding: 42, textAlign: "center", color: "var(--text-secondary)" }}>No engines match these filters.</td></tr>}</tbody></TableSurface></div>}<Pager page={page} pages={pages} total={filtered.length} onPage={setPage} /></Card>;
}

function Verticals({ data, loading }: { data: EngineVerticalUsage | null; loading: boolean }) {
  const [search, setSearch] = useState(""); const [disabled, setDisabled] = useState(false);
  const rows = (data?.verticals ?? []).filter(v => (disabled || v.is_enabled) && (!search || `${v.label} ${v.key}`.toLowerCase().includes(search.toLowerCase())));
  return <div style={{ display: "grid", gap: 16 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: 12 }}><Metric label="Enabled verticals" value={data?.summary.enabled ?? 0} note="Eligible for tenant traffic" tone="success" icon={<Layers3 size={18} />} /><Metric label="Disabled verticals" value={data?.summary.disabled ?? 0} note="Isolated from production" icon={<Lock size={18} />} /><Metric label="Engine bindings" value={data?.summary.mapping_count ?? 0} note="Across every vertical" icon={<GitBranch size={18} />} /><Metric label="Legacy mappings" value={data?.summary.legacy_mapping_count ?? 0} note="Resolved to canonical keys" tone={(data?.summary.legacy_mapping_count ?? 0) ? "warning" : "success"} icon={<AlertTriangle size={18} />} /></div><Card><div style={{ display: "flex", justifyContent: "space-between", gap: 12, marginBottom: 16 }}><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search vertical" style={{ ...input, width: 340 }} /><label style={{ display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: "var(--text-secondary)" }}><input type="checkbox" checked={disabled} onChange={e => setDisabled(e.target.checked)} />Include disabled future verticals</label></div>{loading && !data ? <LoadingRows /> : rows.map(v => <div key={v.id} style={{ border: "1px solid var(--border)", borderRadius: "var(--radius-lg)", marginBottom: 12, overflow: "hidden" }}><div style={{ display: "flex", alignItems: "center", gap: 12, padding: "14px 16px", background: "var(--surface-sunken)" }}><Layers3 size={17} color={v.is_enabled ? "var(--success)" : "var(--text-tertiary)"} /><div style={{ flex: 1 }}><div style={{ fontSize: 14, fontWeight: 700 }}>{v.label}</div><code style={{ fontSize: 10, color: "var(--text-tertiary)" }}>{v.key}</code></div><Badge variant={v.is_enabled ? "success" : "muted"}>{v.is_enabled ? "Enabled" : "Disabled"}</Badge><Badge variant="muted">{v.release_stage}</Badge><Link href={`/admin/verticals/${v.key}?tab=capabilities`}><Btn size="xs" variant="secondary">Manage vertical</Btn></Link></div><div style={{ display: "flex", flexWrap: "wrap", gap: 8, padding: 14 }}>{v.engines.map(e => <div key={`${v.key}-${e.source_key}`} style={{ padding: "8px 10px", border: "1px solid var(--border)", borderRadius: "var(--radius-md)", display: "flex", gap: 7, alignItems: "center" }}>{e.registered ? <CheckCircle2 size={13} color="var(--success)" /> : <AlertTriangle size={13} color="var(--danger)" />}<code style={{ fontSize: 11 }}>{e.engine_key}</code>{e.is_required && <Badge variant="muted">Required</Badge>}{e.uses_legacy_alias && <Badge variant="warning">Alias: {e.source_key}</Badge>}</div>)}</div></div>)}</Card></div>;
}

function Dependencies({ data, loading }: { data: EngineControlPlane | null; loading: boolean }) {
  const [search, setSearch] = useState("");
  const byKey = new Map((data?.engines ?? []).map(item => [item.engine_key, item]));
  const relevant = (data?.engines ?? []).filter(item => item.is_core || item.active_vertical_count > 0);
  const allEdges = relevant.flatMap(item => item.dependencies.map(target => ({ from: item.engine_key, to: target, available: byKey.get(target)?.mounted ?? false })));
  const edges = allEdges.filter(e => !search || `${e.from} ${e.to}`.toLowerCase().includes(search.toLowerCase()));
  const blocked = allEdges.filter(edge => !edge.available);
  return <div style={{ display: "grid", gap: 16 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(3,minmax(0,1fr))", gap: 12 }}><Metric label="Runtime nodes" value={data?.engines.length ?? 0} note="Canonical dependency graph" icon={<Cpu size={18} />} /><Metric label="Dependency edges" value={allEdges.length} note="Declared upstream requirements" icon={<GitBranch size={18} />} /><Metric label="Unavailable dependencies" value={blocked.length} note="Target route is not mounted" tone={blocked.length ? "danger" : "success"} icon={<AlertTriangle size={18} />} /></div><Card><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16 }}><div><h3 style={{ margin: 0, fontSize: 16 }}>Canonical dependency graph</h3><p style={{ margin: "5px 0 0", fontSize: 12, color: "var(--text-secondary)" }}>Legacy database aliases are excluded from this runtime view.</p></div><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Filter dependencies" style={input} /></div>{loading && !data ? <LoadingRows /> : <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(280px,1fr))", gap: 10 }}>{edges.map((e, i) => <div key={`${e.from}-${e.to}-${i}`} style={{ display: "grid", gridTemplateColumns: "1fr auto 1fr", gap: 8, alignItems: "center", padding: 12, border: `1px solid ${e.available ? "var(--border)" : "color-mix(in srgb, var(--danger) 35%, var(--border))"}`, borderRadius: "var(--radius-md)" }}><code style={{ fontSize: 11 }}>{e.from}</code><ChevronRight size={14} color="var(--text-tertiary)" /><div><code style={{ fontSize: 11 }}>{e.to}</code><div style={{ marginTop: 4 }}><Badge variant={e.available ? "success" : "danger"}>{e.available ? "Available" : "Not mounted"}</Badge></div></div></div>)}</div>}</Card></div>;
}

function Overrides() {
  const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [page, setPage] = useState(1);
  const result = useApi(useCallback(() => engineMgmtApi.listTenantOverrides({ status: status || undefined, page, limit: 50 }), [status, page]), [status, page]);
  const [revoke, setRevoke] = useState<EnterpriseTenantOverride | null>(null); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false);
  const rows = (result.data?.overrides ?? []).filter(i => !search || `${i.tenant_id} ${i.engine_key} ${i.reason}`.toLowerCase().includes(search.toLowerCase())); const pages = Math.max(1, Math.ceil((result.data?.meta.total ?? 0) / 50));
  async function doRevoke() { if (!revoke || !reason.trim()) return; setBusy(true); try { await engineMgmtApi.revokeTenantOverride(revoke.tenant_id, revoke.id, reason.trim()); setRevoke(null); setReason(""); result.refetch(); } finally { setBusy(false); } }
  return <><Card><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16, gap: 12 }}><div><h3 style={{ margin: 0, fontSize: 16 }}>Tenant exceptions</h3><p style={{ margin: "5px 0 0", fontSize: 12, color: "var(--text-secondary)" }}>Time-bound, auditable exceptions to normal resolution.</p></div><div style={{ display: "flex", gap: 8 }}><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search tenant or engine" style={{ ...input, width: 230 }} /><select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }} style={input}><option value="">All statuses</option><option value="active">Active</option><option value="revoked">Revoked</option><option value="expired">Expired</option></select></div></div>{result.loading && !result.data ? <LoadingRows /> : <div style={{ overflowX: "auto", border: "1px solid var(--border)", borderRadius: "var(--radius-lg)" }}><TableSurface style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr>{["Tenant", "Engine", "Exception", "Status", "Reason", "Expiry", ""].map(h => <th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{rows.map(i => <tr key={i.id}><td style={td}><code style={{ fontSize: 11 }}>{i.tenant_id}</code></td><td style={td}><code style={{ fontSize: 11, fontWeight: 700 }}>{i.engine_key}</code></td><td style={td}><Badge variant="muted">{i.override_type.replaceAll("_", " ")}</Badge></td><td style={td}><Badge variant={i.status === "active" ? "success" : "muted"}>{i.status}</Badge></td><td style={{ ...td, maxWidth: 260 }}>{i.reason || "—"}</td><td style={td}>{i.expires_at ? new Date(i.expires_at).toLocaleDateString() : "No expiry"}</td><td style={td}>{i.status === "active" && <Btn size="xs" variant="danger" onClick={() => setRevoke(i)}>Revoke</Btn>}</td></tr>)}{!rows.length && <tr><td colSpan={7} style={{ padding: 42, textAlign: "center", color: "var(--text-secondary)" }}>No tenant exceptions match these filters.</td></tr>}</tbody></TableSurface></div>}<Pager page={page} pages={pages} total={result.data?.meta.total ?? 0} onPage={setPage} /></Card><Modal open={!!revoke} onClose={() => setRevoke(null)} title="Revoke tenant exception"><p style={{ fontSize: 13, color: "var(--text-secondary)" }}>This immediately returns the tenant to standard engine resolution. The action is permanently audited.</p><textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Required reason" rows={3} style={{ ...input, width: "100%", height: 86, paddingTop: 10 }} /><div style={{ display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 14 }}><Btn variant="secondary" onClick={() => setRevoke(null)}>Cancel</Btn><Btn variant="danger" disabled={!reason.trim() || busy} loading={busy} onClick={doRevoke}>Revoke exception</Btn></div></Modal></>;
}

function Health({ control }: { control: EngineControlPlane | null }) {
  const result = useApi(useCallback(() => engineMgmtApi.getHealth(), []), []); const [busy, setBusy] = useState(false); const [search, setSearch] = useState(""); const [state, setState] = useState("");
  async function run() { setBusy(true); try { await engineMgmtApi.checkAllHealth(); await result.refetch(); } finally { setBusy(false); } }
  const mounted = new Map((control?.engines ?? []).map(i => [i.database_key ?? i.engine_key, i.mounted])); const now = Date.now(); const all = result.data?.engines ?? [];
  const rows = all.map(i => ({ ...i, stale: !i.last_check || now - new Date(i.last_check).getTime() > 86400000, mounted: mounted.get(i.engine_key) ?? false })).filter(i => (!search || `${i.display_name} ${i.engine_key}`.toLowerCase().includes(search.toLowerCase())) && (!state || (state === "stale" ? i.stale : state === "unmounted" ? !i.mounted : i.health_status === state)));
  const stale = all.filter(i => !i.last_check || now - new Date(i.last_check).getTime() > 86400000).length;
  return <div style={{ display: "grid", gap: 16 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(5,minmax(0,1fr))", gap: 12 }}><Metric label="Healthy" value={result.data?.summary.healthy ?? 0} note="Last persisted probe" tone="success" icon={<CheckCircle2 size={18} />} /><Metric label="Degraded" value={result.data?.summary.degraded ?? 0} note="Partial failure" tone="warning" icon={<AlertTriangle size={18} />} /><Metric label="Down" value={result.data?.summary.down ?? 0} note="Probe failed" tone="danger" icon={<CircleOff size={18} />} /><Metric label="Unknown" value={result.data?.summary.unknown ?? 0} note="Never probed" icon={<Clock3 size={18} />} /><Metric label="Stale probes" value={stale} note="Older than 24 hours" tone={stale ? "warning" : "success"} icon={<Clock3 size={18} />} /></div><Card><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16, gap: 12 }}><div><h3 style={{ margin: 0, fontSize: 16 }}>Operational checks</h3><p style={{ margin: "5px 0 0", fontSize: 12, color: "var(--text-secondary)" }}>Route mounting is separate from dependency and database probes.</p></div><div style={{ display: "flex", gap: 8 }}><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search engine" style={input} /><select value={state} onChange={e => setState(e.target.value)} style={input}><option value="">All states</option><option value="healthy">Healthy</option><option value="degraded">Degraded</option><option value="down">Down</option><option value="stale">Stale</option><option value="unmounted">Not mounted</option></select><Btn onClick={run} loading={busy}><RefreshCw size={13} />Run checks</Btn></div></div>{result.loading && !result.data ? <LoadingRows /> : <div style={{ overflowX: "auto", border: "1px solid var(--border)", borderRadius: "var(--radius-lg)" }}><TableSurface style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr>{["Engine", "Route", "Probe", "Freshness", "Last check", "Error"].map(h => <th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{rows.map(i => <tr key={i.engine_key}><td style={td}><div style={{ fontWeight: 650 }}>{i.display_name}</div><code style={{ fontSize: 10, color: "var(--text-tertiary)" }}>{i.engine_key}</code></td><td style={td}><Badge variant={i.mounted ? "success" : "danger"}>{i.mounted ? "Mounted" : "Not mounted"}</Badge></td><td style={td}><Badge variant={i.health_status === "healthy" ? "success" : i.health_status === "degraded" ? "warning" : i.health_status === "down" ? "danger" : "muted"}>{i.health_status}</Badge></td><td style={td}><Badge variant={i.stale ? "warning" : "success"}>{i.stale ? "Stale" : "Current"}</Badge></td><td style={td}>{i.last_check ? new Date(i.last_check).toLocaleString() : "Never"}</td><td style={{ ...td, color: i.last_error ? "var(--danger)" : "var(--text-tertiary)" }}>{i.last_error || "—"}</td></tr>)}</tbody></TableSurface></div>}</Card></div>;
}

function Access() {
  const [search, setSearch] = useState(""); const [scope, setScope] = useState(""); const [risk, setRisk] = useState("");
  const result = useApi(useCallback(() => rolesPermissionsApi.listPermissions({ search: search || undefined, app_scope: scope || undefined, risk_level: risk || undefined }), [search, scope, risk]), [search, scope, risk]); const s = result.data?.summary;
  return <div style={{ display: "grid", gap: 16 }}><div style={{ display: "grid", gridTemplateColumns: "repeat(4,minmax(0,1fr))", gap: 12 }}><Metric label="Permissions" value={s?.total_permissions ?? 0} note="Code-enforced RBAC keys" icon={<KeyRound size={18} />} /><Metric label="High risk" value={s?.high_risk_permissions ?? 0} note="Destructive or sensitive" tone="warning" icon={<AlertTriangle size={18} />} /><Metric label="Tenant scope" value={s?.tenant_permissions ?? 0} note="Tenant and staff access" icon={<Users size={18} />} /><Metric label="Unassigned" value={s?.unassigned_permissions ?? 0} note="No role grants access" tone={(s?.unassigned_permissions ?? 0) ? "warning" : "success"} icon={<CircleOff size={18} />} /></div><Card><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16 }}><div><h3 style={{ margin: 0, fontSize: 16 }}>Canonical RBAC catalog</h3><p style={{ margin: "5px 0 0", fontSize: 12, color: "var(--text-secondary)" }}>This replaces the unused duplicate engine-permissions table.</p></div><Link href="/admin/users/roles"><Btn variant="secondary">Manage roles</Btn></Link></div><div style={{ display: "grid", gridTemplateColumns: "1fr 180px 180px", gap: 8, marginBottom: 16 }}><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search permission" style={input} /><select value={scope} onChange={e => setScope(e.target.value)} style={input}><option value="">All app scopes</option><option value="admin">Admin</option><option value="tenant">Tenant</option><option value="customer">Customer</option></select><select value={risk} onChange={e => setRisk(e.target.value)} style={input}><option value="">All risk levels</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></div>{result.loading && !result.data ? <LoadingRows /> : <div style={{ overflowX: "auto", maxHeight: 620, border: "1px solid var(--border)", borderRadius: "var(--radius-lg)" }}><TableSurface style={{ width: "100%", borderCollapse: "collapse" }}><thead style={{ position: "sticky", top: 0 }}><tr>{["Permission", "Module", "Scope", "Risk", "Assigned roles"].map(h => <th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{(result.data?.items ?? []).map(i => <tr key={i.permission_key}><td style={td}><code style={{ fontSize: 11, fontWeight: 700 }}>{i.permission_key}</code><div style={{ fontSize: 11, color: "var(--text-tertiary)", marginTop: 4 }}>{i.description}</div></td><td style={td}><Badge variant="muted">{i.module}</Badge></td><td style={td}>{i.app_scope}</td><td style={td}><Badge variant={i.risk_level === "high" ? "danger" : i.risk_level === "medium" ? "warning" : "muted"}>{i.risk_level}</Badge></td><td style={td}>{i.assigned_role_count} roles</td></tr>)}</tbody></TableSurface></div>}</Card></div>;
}

function Audit() {
  const [engine, setEngine] = useState(""); const [action, setAction] = useState(""); const [scope, setScope] = useState(""); const [page, setPage] = useState(1); const [probes, setProbes] = useState(false);
  const result = useApi(useCallback(() => engineMgmtApi.listAuditLogs({ engine_key: engine || undefined, action_type: action || undefined, scope_type: scope || undefined, exclude_health_checks: !probes, page, limit: 50 }), [engine, action, scope, probes, page]), [engine, action, scope, probes, page]); const rows = result.data?.logs ?? []; const meta = result.data?.meta;
  return <Card><div style={{ display: "flex", justifyContent: "space-between", marginBottom: 16 }}><div><h3 style={{ margin: 0, fontSize: 16 }}>Governance audit trail</h3><p style={{ margin: "5px 0 0", fontSize: 12, color: "var(--text-secondary)" }}>Human changes are prioritized; automated probe noise is hidden by default.</p></div><Badge variant="muted">{meta?.total ?? 0} events</Badge></div><div style={{ display: "grid", gridTemplateColumns: "1fr 210px 170px auto", gap: 8, alignItems: "center", marginBottom: 16 }}><input value={engine} onChange={e => { setEngine(e.target.value); setPage(1); }} placeholder="Engine key" style={input} /><input value={action} onChange={e => { setAction(e.target.value); setPage(1); }} placeholder="Exact action type" style={input} /><select value={scope} onChange={e => { setScope(e.target.value); setPage(1); }} style={input}><option value="">All scopes</option><option value="global">Global</option><option value="category">Category</option><option value="tenant">Tenant</option></select><label style={{ fontSize: 12, color: "var(--text-secondary)" }}><input type="checkbox" checked={probes} onChange={e => setProbes(e.target.checked)} /> Include health probes</label></div>{result.loading && !result.data ? <LoadingRows /> : <div style={{ overflowX: "auto", border: "1px solid var(--border)", borderRadius: "var(--radius-lg)" }}><TableSurface style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr>{["Time", "Engine", "Action", "Scope", "Actor", "Reason"].map(h => <th key={h} style={th}>{h}</th>)}</tr></thead><tbody>{rows.map((i: EnterpriseEngineAuditLog) => <tr key={i.id}><td style={td}>{new Date(i.created_at).toLocaleString()}</td><td style={td}><code style={{ fontSize: 11 }}>{i.engine_key || "platform"}</code></td><td style={td}><Badge variant={i.action_type.includes("disable") || i.action_type.includes("revoke") ? "danger" : i.action_type.includes("enable") ? "success" : "muted"}>{i.action_type}</Badge></td><td style={td}>{i.scope_type || "global"}</td><td style={td}><code style={{ fontSize: 10 }}>{i.actor_user_id?.slice(0, 8) || i.actor_role || "system"}</code></td><td style={{ ...td, maxWidth: 300 }}>{i.reason || "—"}</td></tr>)}{!rows.length && <tr><td colSpan={6} style={{ padding: 42, textAlign: "center", color: "var(--text-secondary)" }}>No human governance events match these filters.</td></tr>}</tbody></TableSurface></div>}<Pager page={page} pages={meta?.total_pages ?? 1} total={meta?.total ?? 0} onPage={setPage} /></Card>;
}

export default function EngineMgmtPage() {
  const [tab, setTab] = useState<Tab>(() => { if (typeof window === "undefined") return "overview"; const q = new URLSearchParams(window.location.search).get("tab"); return q && TABS.some(i => i.id === q) ? q as Tab : q ? LEGACY_TAB_REDIRECTS[q] ?? "overview" : "overview"; });
  const control = useApi(useCallback(() => engineMgmtApi.getControlPlane(), []), []); const verticals = useApi(useCallback(() => engineMgmtApi.getVerticalUsage(), []), []);
  const refresh = async () => { await Promise.all([control.refetch(), verticals.refetch()]); };
  const choose = (next: Tab) => { setTab(next); const url = new URL(window.location.href); url.searchParams.set("tab", next); window.history.replaceState({}, "", url); };
  return <AdminLayout><SectionHeader title="Engine command center" subtitle="Runtime truth, vertical rollout, tenant exceptions, health, and access governance" icon={<Cpu />} actions={<div style={{ display: "flex", gap: 8 }}><Link href="/admin/engines/resolver"><Btn variant="secondary" size="sm"><Filter size={13} />Access resolver</Btn></Link><Btn size="sm" variant="secondary" onClick={refresh}><RefreshCw size={13} />Refresh</Btn></div>} />
    <div style={{ marginBottom: 18, padding: "12px 14px", border: "1px solid color-mix(in srgb, var(--text-link) 28%, var(--border))", borderRadius: "var(--radius-lg)", background: "color-mix(in srgb, var(--text-link) 5%, var(--surface))", display: "flex", alignItems: "center", gap: 10 }}><ShieldCheck size={17} color="var(--text-link)" /><div style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.5 }}><strong style={{ color: "var(--text-primary)" }}>Runtime-aware governance.</strong> Category choices stay in Catalog, finance stays in Home Services Finance, and RBAC is the single access-control source.</div></div>
    <nav aria-label="Engine management sections" style={{ display: "flex", gap: 4, borderBottom: "1px solid var(--border)", marginBottom: 20, overflowX: "auto" }}>{TABS.map(i => <button key={i.id} onClick={() => choose(i.id)} style={{ display: "inline-flex", alignItems: "center", gap: 7, padding: "11px 13px", border: 0, borderBottom: tab === i.id ? "2px solid var(--text-link)" : "2px solid transparent", background: tab === i.id ? "color-mix(in srgb, var(--text-link) 7%, transparent)" : "transparent", color: tab === i.id ? "var(--text-link)" : "var(--text-secondary)", fontSize: 12, fontWeight: tab === i.id ? 700 : 550, cursor: "pointer", whiteSpace: "nowrap", marginBottom: -1, borderRadius: "var(--radius-md) var(--radius-md) 0 0" }}>{i.icon}{i.label}</button>)}</nav>
    {tab === "overview" && <Overview data={control.data} loading={control.loading} />}{tab === "runtime" && <Runtime data={control.data} loading={control.loading} />}{tab === "verticals" && <Verticals data={verticals.data} loading={verticals.loading} />}{tab === "dependencies" && <Dependencies data={control.data} loading={control.loading} />}{tab === "overrides" && <Overrides />}{tab === "health" && <Health control={control.data} />}{tab === "access" && <Access />}{tab === "audit" && <Audit />}
  </AdminLayout>;
}
