/** Product copy and suggestion content for the four reference experiences.
 * Keeping it outside render functions makes the UI reusable and gives future
 * localization/config work one stable boundary. */
export const customerExperienceCopy = {
  splash: {
    accessibilityLabel: "Loading Fuvay",
    tagline: "HOME SERVICES, DONE RIGHT",
    loadingLabel: "LOADING YOUR HOME",
  },
  login: {
    eyebrow: "SIGN IN",
    title: "Your home,\none number away.",
    otpDescription: "Enter your mobile number and we'll send a one-time code — no password to remember.",
    passwordDescription: "Use your email or mobile number and password to securely access your home.",
    newCustomer: "New to Fuvay?",
    createAccount: "Create account",
    reassurance: {
      fastCode: "Code arrives in about 10 seconds",
      privateNumber: "Your number is never shared with pros",
      flexibleBooking: "Track and reschedule any booking",
    },
  },
  home: {
    headline: "Every home fix, one tap away.",
    searchPlaceholder: "Try “AC not cooling”",
    sections: {
      services: "Popular services",
      liveBooking: "Live booking",
      activeBookings: "More active bookings",
      recommendations: "Recommended for you",
      popular: "Popular near you",
      categories: "Browse by category",
      spotlights: "Spotlights",
      coverPlans: "Cover plans",
      specialists: "Top-rated specialists near you",
    },
    specialistSubtitle: "Vetted, background-checked, ready near you",
    offer: {
      eyebrow: "LIMITED OFFER",
      title: "Flat 30% off AC servicing",
      subtitle: "Book this week and keep your home cool for less.",
      action: "Claim",
    },
    nextVisit: "NEXT VISIT",
    liveBooking: "LIVE BOOKING",
    upcomingCount: "3 UPCOMING",
    recommendationSubtitle: "Based on your home and last visits",
    festive: {
      eyebrow: "FESTIVE SEASON",
      title: "Festival deep clean\nfor a spotless home",
      subtitle: "Full-home clean plus kitchen degrease, done in one visit.",
      offer: "₹500",
      offerLabel: "OFF",
      action: "Grab offer",
      deadline: "ENDS THIS WEEK",
    },
    assistant: {
      eyebrow: "AI ASSISTANT · BETA",
      title: "Not sure what's broken?",
      subtitle: "Describe it in your words — get a likely cause, a price range, and the right service booked.",
      prompts: ["AC blowing warm air", "Low water pressure", "Power keeps tripping"],
      responseTime: "ANSWERS IN ~10s",
      action: "Ask AI",
    },
    fallbacks: {
      customerName: "Fuvay customer",
      location: "Choose service location",
      nextVisitTime: "Today, 2:40 PM",
      activeService: "Home service & repair",
      activeTime: "Today · 2:00–4:00 PM",
      activeProvider: "Verified Fuvay professional",
      activeStatus: "PRO ON THE WAY",
      activeNote: "Your professional is preparing for the visit.",
    },
  },
  assistant: {
    title: "Fuvay assistant",
    online: "Online · replies instantly",
    pickerTitle: "What can we help with?",
    pickerSubtitle: "Choose a service or describe the problem in your own words.",
    loading: "Loading your assistant",
    chooseLocation: "Choose your location first",
    chooseLocationBody: "Fuvay Assistant needs your service location to check what's available.",
    composerIdle: "Choose an option above to continue",
    composerReview: "Fuvay AI is finishing your booking…",
    composerBooked: "Your booking is confirmed",
  },
} as const;
